import { RiseOutlined } from '@ant-design/icons'
import { GraviButton, Texto, Vertical } from '@gravitate-js/excalibrr'
import type { IndexOfferFormulaComponent, IndexPricingFormData, SpecialOfferMetadataResponseData } from '../../../../ManageOffers.types'
import { AdditionalTerms } from './Components/AdditionalTerms'
import { ConfiguredPriceDisplay } from './Components/ConfiguredPriceDisplay'
import { DrawerFooter } from './Components/DrawerFooter'
import { DrawerTitle } from './Components/DrawerTitle'
import { FormulaComponentBuilder } from './Components/FormulaComponentBuilder'
import { FormulaDiff } from './Components/FormulaDiff'
import { FormulaDisplayName } from './Components/FormulaDisplayName'
import { ReferenceData } from './Components/ReferenceData'
import { generateIndexOfferDisplayName } from './Components/IndexOfferComponentsColumnDefs'
import { mapToFormulaMetadata } from './Utils/TemplateHelpers'
import { Drawer, Form } from 'antd'
import type { FormInstance } from 'antd'
import type { MutableRefObject } from 'react'
import { useEffect, useMemo, useState } from 'react'

export interface ConfigureIndexPriceProps {
  metadata: SpecialOfferMetadataResponseData | undefined
  onSaveIndexPricing: (data: IndexPricingFormData | null) => void
  savedIndexData?: IndexPricingFormData | null
  isAuction: boolean
  idRef: MutableRefObject<number>
  showIndexError: boolean
  setShowIndexError: React.Dispatch<React.SetStateAction<boolean>>
  formulaForm: FormInstance
  offerForm: FormInstance
  selectedProductLocation: number
}

export function ConfigureIndexPrice({
  metadata,
  onSaveIndexPricing,
  savedIndexData,
  isAuction,
  idRef,
  showIndexError,
  setShowIndexError,
  formulaForm,
  offerForm,
  selectedProductLocation,
}: ConfigureIndexPriceProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [formulaComponents, setFormulaComponents] = useState<IndexOfferFormulaComponent[]>([])
  const [showCustomInputForSeller, setShowCustomInputForSeller] = useState(false)
  const [showCustomInputForBuyer, setShowCustomInputForBuyer] = useState(false)

  const onOpen = () => {
    const selection = metadata?.ProductLocationSelections?.find((s) => s.TradeEntrySetupId == selectedProductLocation)
    const LocationId = selection ? selection.LocationId.toString() : undefined
    const ProductId = selection ? selection.ProductId.toString() : undefined

    if (savedIndexData) {
      formulaForm.setFieldsValue({ ...savedIndexData, ProductId, LocationId })
      setFormulaComponents(savedIndexData.formulaComponents)
      setShowCustomInputForSeller(!!savedIndexData.InternalDisplayName)
      setShowCustomInputForBuyer(!!savedIndexData.ExternalDisplayName)
    } else {
      formulaForm.setFieldsValue({ ProductId, LocationId })
      setFormulaComponents([])
    }
  }

  useEffect(() => {
    if (isOpen) onOpen()
  }, [isOpen, savedIndexData])

  const onFinish = (values: any) => {
    const indexData: IndexPricingFormData = {
      ...values,
      FormulaDifferential: values.FormulaDifferential ?? 0,
      formulaComponents,
    }
    onSaveIndexPricing?.(indexData)
    setShowIndexError(false)
    offerForm.setFieldsValue({ ReservePrice: values.ReservePrice })
    setIsOpen(false)
  }

  const handleClose = () => {
    setIsOpen(false)
    setFormulaComponents(savedIndexData?.formulaComponents || [])
    formulaForm.resetFields()
    setShowCustomInputForSeller(false)
    setShowCustomInputForBuyer(false)
  }

  const formulaMetadata = useMemo(() => mapToFormulaMetadata(metadata?.IndexOfferMetaData), [metadata?.IndexOfferMetaData])

  const autoGeneratedFormulaName = useMemo(() => {
    if (!formulaComponents?.length) return 'No components added yet'
    return formulaComponents.map((c) => {
      if (c.isDisplayNameCustomized && c.DisplayName) return c.DisplayName
      return generateIndexOfferDisplayName(c, metadata?.IndexOfferMetaData)
    }).join(' + ')
  }, [formulaComponents, formulaMetadata])

  return (
    <>
      <Vertical>
        <Texto category={'h4'} className={'text-18'}>Set Index Price</Texto>
        <Texto className={'mb-4 text-14'}>Configure index based pricing for your offer</Texto>
      </Vertical>

      {savedIndexData && formulaComponents.length > 0 ? (
        <ConfiguredPriceDisplay
          savedIndexData={savedIndexData}
          onSaveIndexPricing={onSaveIndexPricing}
          formula={autoGeneratedFormulaName}
          openConfig={setIsOpen}
          isAuction={isAuction}
          metadata={metadata}
        />
      ) : (
        <Vertical
          className={'bordered border-radius-10 p-4 gap-10'}
          style={showIndexError ? { borderColor: 'var(--theme-error)' } : {}}
          verticalCenter
          horizontalCenter
        >
          <RiseOutlined style={{ fontSize: '50px', color: 'var(--gray-500)' }} />
          <Texto category={'h5'}>No Index Price Configured</Texto>
          <Texto className={'text-14'}>Set up an index based pricing strategy</Texto>
          <GraviButton
            className={'mt-2'}
            buttonText={<Texto weight={'normal'} className={'text-14'}>Build Index Price</Texto>}
            onClick={() => setIsOpen(true)}
          />
        </Vertical>
      )}

      <Drawer
        className={'create-index-drawer'}
        title={<DrawerTitle handleClose={handleClose} />}
        open={isOpen}
        onClose={handleClose}
        placement={'bottom'}
        height={'85vh'}
        closable={false}
        footer={<DrawerFooter form={formulaForm} handleClose={handleClose} />}
      >
        <Form onFinish={onFinish} form={formulaForm} layout={'vertical'}>
          <Vertical className={'gap-24'}>
            <ReferenceData metadata={metadata} selectedProductLocation={selectedProductLocation} />
            <FormulaDisplayName
              formula={autoGeneratedFormulaName}
              form={formulaForm}
              setShowCustomInputForBuyer={setShowCustomInputForBuyer}
              showCustomInputForSeller={showCustomInputForSeller}
              setShowCustomInputForSeller={setShowCustomInputForSeller}
              showCustomInputForBuyer={showCustomInputForBuyer}
            />
            <FormulaComponentBuilder
              metadata={metadata}
              formulaComponents={formulaComponents}
              setFormulaComponents={setFormulaComponents}
              form={formulaForm}
              idRef={idRef}
            />
            <AdditionalTerms metadata={metadata} />
            <FormulaDiff isAuction={isAuction} />
          </Vertical>
        </Form>
      </Drawer>
    </>
  )
}
