/**
 * Server Management Best Practices for Excalibrr MCP Generated Projects
 *
 * This file defines operational rules and utilities to prevent server conflicts
 * and resource waste when working with generated React demos.
 */

export function generateServerManagementREADME(): string {
  return `# Server Management Guide

## 🚨 Important Server Rules

### Rule #1: ONE SERVER PER PROJECT
**Never run multiple dev servers for the same project!**

### Rule #2: Check Before Starting
Always check for existing servers before starting a new one:

\`\`\`bash
# Check what's running
npm run dev:check
# or
ps aux | grep vite | grep your-project-name
\`\`\`

### Rule #3: Clean Start
If you need to restart the server:

\`\`\`bash
# Stop existing server first
npm run stop
# Then start clean
npm run dev

# Or use the clean command (stops + starts)
npm run dev:clean
\`\`\`

## 🔧 Available Commands

- \`npm run dev\` - Start development server
- \`npm run dev:clean\` - Stop existing + start fresh server  
- \`npm run dev:check\` - Check if servers are running
- \`npm run stop\` - Stop all project servers

## ⚠️ Common Issues

### "Port 3001 is in use, trying another one..."
**Problem**: Another server is already running
**Solution**: Use \`npm run dev:clean\` instead of \`npm run dev\`

### Multiple servers on different ports
**Problem**: Started new servers without stopping old ones
**Solution**: Run \`npm run stop\` then \`npm run dev\`

## 🎯 Best Practices

1. **Always use \`dev:clean\`** when unsure about server state
2. **Check terminal output** for the actual port being used
3. **One browser tab per server** - avoid confusion
4. **Stop servers** when switching between projects

---
*Generated by Excalibrr MCP Server*
`;
}

export function generateServerCheckScript(): string {
  return `#!/bin/bash
# Server Management Utility for Excalibrr Generated Projects

PROJECT_NAME="$(basename $(pwd))"
VITE_PATTERN="vite.*$PROJECT_NAME"

check_servers() {
    echo "🔍 Checking for running servers..."
    RUNNING=$(ps aux | grep "$VITE_PATTERN" | grep -v grep)
    
    if [ -z "$RUNNING" ]; then
        echo "✅ No servers running for $PROJECT_NAME"
        return 0
    else
        echo "⚠️  Found running servers:"
        echo "$RUNNING"
        return 1
    fi
}

stop_servers() {
    echo "🛑 Stopping all servers for $PROJECT_NAME..."
    pkill -f "$VITE_PATTERN" 2>/dev/null || true
    sleep 2
    check_servers
}

start_clean() {
    echo "🧹 Starting clean server for $PROJECT_NAME..."
    stop_servers
    echo "🚀 Starting development server..."
    npm run dev
}

case "$1" in
    "check")
        check_servers
        ;;
    "stop")
        stop_servers
        ;;
    "clean")
        start_clean
        ;;
    *)
        echo "Usage: $0 {check|stop|clean}"
        echo "  check - Check for running servers"
        echo "  stop  - Stop all project servers"  
        echo "  clean - Stop existing + start fresh server"
        ;;
esac
`;
}

export const SERVER_MANAGEMENT_RULES = {
  RULE_1: "ONE_SERVER_PER_PROJECT",
  RULE_2: "CHECK_BEFORE_STARTING",
  RULE_3: "USE_CLEAN_COMMANDS",
  RULE_4: "STOP_WHEN_SWITCHING_PROJECTS",
} as const;
