// Static HTML files and manifest generators

export function generateIndexHtml(featureName: string) {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="${featureName} Demo - Generated by Excalibrr MCP Server" />
    <link rel="manifest" href="/manifest.json" />
    <title>Gravitate Demo</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>`;
}

// CRITICAL FIX: Add manifest.json generation
export function generateManifestJson() {
  const manifest = {
    short_name: "React App",
    name: "Create React App Sample",
    icons: [
      {
        src: "favicon.ico",
        sizes: "64x64 32x32 24x24 16x16",
        type: "image/x-icon",
      },
    ],
    start_url: ".",
    display: "standalone",
    theme_color: "#000000",
    background_color: "#ffffff",
  };

  return JSON.stringify(manifest, null, 2);
}

export function generateRootIndexHtml() {
  return `<!DOCTYPE html>
<html lang="en-US" xml:lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta http-equiv="Content-Language" content="en" />
    <link rel="manifest" href="/manifest.json" />
    <title>Gravitate Demo</title>
  </head>

  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>

    <!-- This is the script tag for bootstrapping your Vite application -->
    <script type="module" src="/src/index.tsx"></script>
  </body>
</html>`;
}

export function generateReadme(featureName: string, componentName: string) {
  return `# ${featureName} Demo

> Generated by Excalibrr MCP Server - A complete React demo project

## 🚀 Quick Start

\`\`\`bash
# Install dependencies with Yarn
yarn install

# Start the development server
yarn dev
\`\`\`

The app will open at [http://localhost:3001](http://localhost:3001)

## 📁 Project Structure

\`\`\`
${featureName.toLowerCase()}-demo/
├── index.html             # Vite entry HTML file
├── package.json           # Yarn-based dependency management
├── vite.config.ts         # Vite build configuration
├── tsconfig.json          # TypeScript configuration
├── eslint.config.js       # ESLint configuration
├── public/
│   └── index.html         # HTML template
└── src/
    ├── index.tsx          # App entry point with AG-Grid CSS imports
    ├── App.tsx            # Main app with navigation setup
    ├── styles.css         # Custom application styles
    ├── components/
    │   ├── ${componentName}.tsx # Your generated grid component
    │   ├── columnDefs.ts   # Grid column definitions
    │   ├── themeConfig.ts  # Theme configuration
    │   └── ThemeComponents/
    │       ├── LightTheme.tsx
    │       └── DarkTheme.tsx
    ├── Theming/           # Theme infrastructure
    │   ├── core.less      # Core theming variables
    │   └── Themes/
    │       ├── Light/
    │       │   ├── light-theme.less
    │       │   └── Light.jsx
    │       └── Dark/
    │           ├── dark-theme.less
    │           └── Dark.jsx
    ├── mocks/
    │   ├── mockScopes.ts   # Navigation permissions
    │   ├── mockPageConfig.tsx # Navigation structure with icons
    │   └── MockUserControlPanel.tsx # Updated with Horizontal/Vertical
    ├── data/
    │   └── dummyData.ts    # Sample data for the grid
    └── api/
        ├── ${featureName.toLowerCase()}Hook.ts # Data fetching hook
        └── types.ts        # TypeScript interfaces
\`\`\`

## 🎨 Features

- **⚡ Vite Build System**: Fast development with Hot Module Replacement
- **📦 Yarn Package Management**: Reliable dependency resolution with yarn resolutions
- **Full Navigation**: Complete sidebar and top navigation using Excalibrr
- **Working Grid**: Functional data grid with sorting, filtering, and search
- **Mock Data**: Sample data that can be easily replaced with real API calls
- **TypeScript**: Full type safety throughout the project
- **ESLint + Modern Config**: Code quality with latest ESLint flat config
- **Responsive Design**: Works on desktop and mobile devices
- **Proper Theming**: Complete theming infrastructure with Light/Dark modes
- **Layout Components**: MockUserControlPanel uses Horizontal/Vertical components

## 🔧 Development Commands

\`\`\`bash
# Development server with hot reload
yarn dev

# Type checking
yarn build:tsc

# Linting
yarn lint
yarn lint:fix

# Production build
yarn build

# Preview production build
yarn preview
\`\`\`

## 🔧 Customization

### Adding Real Data

1. Edit \`src/api/${featureName.toLowerCase()}Hook.ts\`
2. Change \`USE_DUMMY_DATA\` to \`false\`
3. Update the API endpoint URL
4. Modify the data types in \`src/api/types.ts\`

### Styling

The project uses Excalibrr's default styling with proper theming infrastructure:

1. Check the theme configuration in \`src/components/themeConfig.ts\`
2. Modify theme styles in \`src/Theming/Themes/\`
3. Component styles use Excalibrr's design system

### Navigation

- Edit \`src/mocks/mockPageConfig.tsx\` to add/remove navigation items
- Update \`src/mocks/mockScopes.ts\` to control permissions
- Icons are properly configured using Ant Design icons

## 🚀 Deployment

\`\`\`bash
# Build for production
yarn build

# Preview the build locally
yarn preview

# Deploy to Vercel, Netlify, or your preferred platform
\`\`\`

## 📚 Learn More

- [Excalibrr Documentation](https://your-excalibrr-docs-url)
- [AG Grid Documentation](https://ag-grid.com/)
- [React Query Documentation](https://tanstack.com/query/)

---

*This project was generated by the Excalibrr MCP Server to help designers quickly prototype and demonstrate UI components.*`;
}
