import type { ExceptionType, ThresholdOverride } from './types.schema'

export type QuoteRow = {
  id: number
  group: string
  product: string
  terminal: string
  isSpread: boolean
  spreadParentId?: number
  tierGroup: string | null
  tierLevel: string | null
  prior_lastPrice: number
  benchmark_ulsd: number
  proposed_price: number
  proposed_delta: number
  proposed_margin: number
  proposed_marketMove: number
  proposed_adjustment: number
  proposed_tierDiff: number | null
  current_tierDiff: number | null
  exceptions: string[]
  profileKey?: string
  exceptionType?: ExceptionType
  exceptionCount?: number
  overrides?: ThresholdOverride[]
}

const tierAssignments: Record<number, { tierGroup: string | null; tierLevel: string | null; proposed_tierDiff: number | null; current_tierDiff: number | null }> = {
  1:  { tierGroup: 'Group A', tierLevel: 'Tier 1', proposed_tierDiff: 0.0025, current_tierDiff: 0.0025 },
  2:  { tierGroup: 'Group A', tierLevel: 'Tier 2', proposed_tierDiff: 0.0050, current_tierDiff: 0.0050 },
  3:  { tierGroup: 'Group A', tierLevel: 'Tier 3', proposed_tierDiff: 0.0075, current_tierDiff: 0.0075 },
  4:  { tierGroup: 'Group B', tierLevel: 'Tier 1', proposed_tierDiff: 0.0030, current_tierDiff: 0.0030 },
  5:  { tierGroup: 'Group B', tierLevel: 'Tier 2', proposed_tierDiff: 0.0055, current_tierDiff: 0.0055 },
  6:  { tierGroup: 'Group A', tierLevel: 'Tier 1', proposed_tierDiff: 0.0025, current_tierDiff: 0.0025 },
  7:  { tierGroup: 'Group B', tierLevel: 'Tier 3', proposed_tierDiff: 0.0080, current_tierDiff: 0.0080 },
  8:  { tierGroup: 'Group C', tierLevel: 'Tier 1', proposed_tierDiff: 0.0020, current_tierDiff: 0.0020 },
  9:  { tierGroup: 'Group C', tierLevel: 'Tier 2', proposed_tierDiff: 0.0045, current_tierDiff: 0.0045 },
  10: { tierGroup: null, tierLevel: null, proposed_tierDiff: null, current_tierDiff: null },
  11: { tierGroup: 'Group C', tierLevel: 'Tier 1', proposed_tierDiff: 0.0020, current_tierDiff: 0.0020 },
  12: { tierGroup: 'Group A', tierLevel: 'Tier 2', proposed_tierDiff: 0.0050, current_tierDiff: 0.0050 },
  13: { tierGroup: 'Group A', tierLevel: 'Tier 1', proposed_tierDiff: 0.0025, current_tierDiff: 0.0025 },
  14: { tierGroup: 'Group B', tierLevel: 'Tier 1', proposed_tierDiff: 0.0030, current_tierDiff: 0.0030 },
  15: { tierGroup: null, tierLevel: null, proposed_tierDiff: null, current_tierDiff: null },
  16: { tierGroup: 'Group A', tierLevel: 'Tier 1', proposed_tierDiff: 0.0025, current_tierDiff: 0.0025 },
  17: { tierGroup: 'Group C', tierLevel: 'Tier 3', proposed_tierDiff: 0.0070, current_tierDiff: 0.0070 },
  18: { tierGroup: null, tierLevel: null, proposed_tierDiff: null, current_tierDiff: null },
  19: { tierGroup: 'Group B', tierLevel: 'Tier 2', proposed_tierDiff: 0.0055, current_tierDiff: 0.0055 },
  20: { tierGroup: 'Group A', tierLevel: 'Tier 3', proposed_tierDiff: 0.0075, current_tierDiff: 0.0075 },
}

const rawQuoteBookData: Omit<QuoteRow, 'tierGroup' | 'tierLevel' | 'proposed_tierDiff' | 'current_tierDiff'>[] = [
  // Wholesale (6 rows)
  {
    id: 1,
    group: 'wholesale',
    product: 'Diesel #2',
    terminal: 'Houston Term.',
    isSpread: false,
    prior_lastPrice: 2.8450,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.8510,
    proposed_delta: 0.0060,
    proposed_margin: 0.0880,
    proposed_marketMove: 0.0045,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },
  {
    id: 2,
    group: 'wholesale',
    product: 'Unleaded 87',
    terminal: 'Houston Term.',
    isSpread: false,
    prior_lastPrice: 2.5280,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.5300,
    proposed_delta: 0.0020,
    proposed_margin: 0.0670,
    proposed_marketMove: 0.0032,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },
  {
    id: 3,
    group: 'wholesale',
    product: 'Diesel #2',
    terminal: 'Dallas Hub',
    isSpread: false,
    prior_lastPrice: 2.8680,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.8700,
    proposed_delta: 0.0020,
    proposed_margin: 0.0320,
    proposed_marketMove: 0.0028,
    proposed_adjustment: 0.0000,
    exceptions: ['Below Min Margin'],
    profileKey: 'marginDefense',
    exceptionType: 'hard',
    exceptionCount: 1,
    overrides: [],
  },
  {
    id: 4,
    group: 'wholesale',
    product: 'Premium 91',
    terminal: 'Houston Term.',
    isSpread: false,
    prior_lastPrice: 3.0120,
    benchmark_ulsd: 2.7630,
    proposed_price: 3.0180,
    proposed_delta: 0.0060,
    proposed_margin: 0.0920,
    proposed_marketMove: 0.0050,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },
  {
    id: 5,
    group: 'wholesale',
    product: 'Diesel #2',
    terminal: 'Chicago Term.',
    isSpread: false,
    prior_lastPrice: 2.9100,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.9050,
    proposed_delta: -0.0050,
    proposed_margin: 0.0640,
    proposed_marketMove: -0.0015,
    proposed_adjustment: 0.0050,
    exceptions: ['Market Move Alert'],
    profileKey: 'standard',
    exceptionType: 'soft',
    exceptionCount: 1,
    overrides: [],
  },
  {
    id: 6,
    group: 'wholesale',
    product: 'Unleaded 87',
    terminal: 'Dallas Hub',
    isSpread: true,
    spreadParentId: 2,
    prior_lastPrice: 2.5400,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.5420,
    proposed_delta: 0.0020,
    proposed_margin: 0.0580,
    proposed_marketMove: 0.0018,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },

  // Industrial (5 rows)
  {
    id: 7,
    group: 'industrial',
    product: 'Diesel #2',
    terminal: 'Houston Term.',
    isSpread: false,
    prior_lastPrice: 2.8200,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.8280,
    proposed_delta: 0.0080,
    proposed_margin: 0.0900,
    proposed_marketMove: 0.0055,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },
  {
    id: 8,
    group: 'industrial',
    product: 'Jet-A',
    terminal: 'Houston Term.',
    isSpread: false,
    prior_lastPrice: 3.1500,
    benchmark_ulsd: 2.7630,
    proposed_price: 3.1560,
    proposed_delta: 0.0060,
    proposed_margin: 0.1100,
    proposed_marketMove: 0.0042,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },
  {
    id: 9,
    group: 'industrial',
    product: 'Diesel #2',
    terminal: 'Chicago Term.',
    isSpread: false,
    prior_lastPrice: 2.8900,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.8850,
    proposed_delta: -0.0050,
    proposed_margin: 0.0350,
    proposed_marketMove: -0.0020,
    proposed_adjustment: 0.0000,
    exceptions: ['Below Min Margin'],
    profileKey: 'marginDefense',
    exceptionType: 'hard',
    exceptionCount: 1,
    overrides: [],
  },
  {
    id: 10,
    group: 'industrial',
    product: 'Unleaded 87',
    terminal: 'Dallas Hub',
    isSpread: false,
    prior_lastPrice: 2.5100,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.5150,
    proposed_delta: 0.0050,
    proposed_margin: 0.0620,
    proposed_marketMove: 0.0030,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },
  {
    id: 11,
    group: 'industrial',
    product: 'Jet-A',
    terminal: 'Dallas Hub',
    isSpread: true,
    spreadParentId: 8,
    prior_lastPrice: 3.1650,
    benchmark_ulsd: 2.7630,
    proposed_price: 3.1700,
    proposed_delta: 0.0050,
    proposed_margin: 0.1050,
    proposed_marketMove: 0.0038,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },

  // Retail (5 rows)
  {
    id: 12,
    group: 'retail',
    product: 'Unleaded 87',
    terminal: 'Houston Term.',
    isSpread: false,
    prior_lastPrice: 2.5990,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.6030,
    proposed_delta: 0.0040,
    proposed_margin: 0.0480,
    proposed_marketMove: 0.0025,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },
  {
    id: 13,
    group: 'retail',
    product: 'Diesel #2',
    terminal: 'Houston Term.',
    isSpread: false,
    prior_lastPrice: 2.8790,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.8830,
    proposed_delta: 0.0040,
    proposed_margin: 0.0560,
    proposed_marketMove: 0.0022,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },
  {
    id: 14,
    group: 'retail',
    product: 'Premium 91',
    terminal: 'Dallas Hub',
    isSpread: false,
    prior_lastPrice: 3.0500,
    benchmark_ulsd: 2.7630,
    proposed_price: 3.0450,
    proposed_delta: -0.0050,
    proposed_margin: 0.0700,
    proposed_marketMove: -0.0018,
    proposed_adjustment: -0.0025,
    exceptions: ['Market Move Alert'],
    profileKey: 'standard',
    exceptionType: 'soft',
    exceptionCount: 1,
    overrides: [],
  },
  {
    id: 15,
    group: 'retail',
    product: 'Unleaded 87',
    terminal: 'Chicago Term.',
    isSpread: false,
    prior_lastPrice: 2.6200,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.6240,
    proposed_delta: 0.0040,
    proposed_margin: 0.0520,
    proposed_marketMove: 0.0028,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },
  {
    id: 16,
    group: 'retail',
    product: 'Diesel #2',
    terminal: 'Dallas Hub',
    isSpread: true,
    spreadParentId: 13,
    prior_lastPrice: 2.8850,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.8890,
    proposed_delta: 0.0040,
    proposed_margin: 0.0540,
    proposed_marketMove: 0.0020,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },

  // Other (4 rows)
  {
    id: 17,
    group: 'other',
    product: 'Jet-A',
    terminal: 'Chicago Term.',
    isSpread: false,
    prior_lastPrice: 3.1800,
    benchmark_ulsd: 2.7630,
    proposed_price: 3.1750,
    proposed_delta: -0.0050,
    proposed_margin: 0.0380,
    proposed_marketMove: -0.0025,
    proposed_adjustment: 0.0000,
    exceptions: ['Below Min Margin'],
    profileKey: 'marginDefense',
    exceptionType: 'hard',
    exceptionCount: 1,
    overrides: [],
  },
  {
    id: 18,
    group: 'other',
    product: 'Diesel #2',
    terminal: 'Dallas Hub',
    isSpread: false,
    prior_lastPrice: 2.8550,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.8600,
    proposed_delta: 0.0050,
    proposed_margin: 0.0780,
    proposed_marketMove: 0.0035,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },
  {
    id: 19,
    group: 'other',
    product: 'Unleaded 87',
    terminal: 'Chicago Term.',
    isSpread: false,
    prior_lastPrice: 2.5450,
    benchmark_ulsd: 2.7630,
    proposed_price: 2.5500,
    proposed_delta: 0.0050,
    proposed_margin: 0.0600,
    proposed_marketMove: 0.0032,
    proposed_adjustment: 0.0000,
    exceptions: [],
    profileKey: 'standard',
    exceptionType: 'clean',
    exceptionCount: 0,
    overrides: [],
  },
  {
    id: 20,
    group: 'other',
    product: 'Premium 91',
    terminal: 'Houston Term.',
    isSpread: false,
    prior_lastPrice: 3.0350,
    benchmark_ulsd: 2.7630,
    proposed_price: 3.0400,
    proposed_delta: 0.0050,
    proposed_margin: 0.0850,
    proposed_marketMove: 0.0040,
    proposed_adjustment: 0.0030,
    exceptions: ['Market Move Alert'],
    profileKey: 'standard',
    exceptionType: 'soft',
    exceptionCount: 1,
    overrides: [],
  },
]

export const quoteBookData: QuoteRow[] = rawQuoteBookData.map(row => ({
  ...row,
  ...tierAssignments[row.id],
}))

export const quoteGroups = [
  { id: 'wholesale', label: 'Wholesale' },
  { id: 'industrial', label: 'Industrial' },
  { id: 'retail', label: 'Retail' },
  { id: 'other', label: 'Other' },
]
