import dayjs, { type Dayjs } from 'dayjs'
import type { FormInstance } from 'antd'

import { dateFormat } from '../formatters'
import { step1Fields, step2Fields } from '../Constants/FormConstants'
import type { CreateSpecialOfferRequest, IndexPricingFormData, IndexOfferMetaData } from '../../ManageOffers.types'
import { convertComponentsToFormula } from '../../components/CreateNew/Util/indexConfigHelpers'

export interface createPayloadFromValuesProps {
  values: any
  indexPricingData?: IndexPricingFormData
  formulaMetadata?: IndexOfferMetaData
}

function getFormulaAutoGeneratedDisplayText(components: any[], _metadata?: IndexOfferMetaData): string {
  if (!components || components.length === 0) return ''
  return components.map((c: any) => c.DisplayName || 'Component').join(' + ')
}

export function createPayloadFromValues({
  values,
  indexPricingData,
  formulaMetadata,
}: createPayloadFromValuesProps): CreateSpecialOfferRequest {
  const tradeEntrySetupIds =
    typeof values.ProductLocation === 'number' ? [values.ProductLocation] : values.ProductLocation
  const InvitationTriggerDateTimeTZ = values.SendInvitesOnCreate
    ? constructDateTime(dayjs(), dayjs().add(1, 'minute'))
    : constructDateTime(values.InviteTriggerDate, values.InviteTriggerTime)

  let indexPricingInfo: any | undefined
  if (indexPricingData) {
    const formula = convertComponentsToFormula(indexPricingData)
    indexPricingInfo = {
      ProductId: indexPricingData.ProductId,
      LocationId: indexPricingData.LocationId,
      EffectiveTime: indexPricingData.PricingEffectiveTimes,
      WeekendRule: indexPricingData.PricingWeekendBehavior,
      HolidayRule: indexPricingData.PricingHolidayBehavior,
      AdditionalFreetextTerms: indexPricingData.AdditionalFreetextTerms,
      PricingFormulaDefaultText: getFormulaAutoGeneratedDisplayText(
        indexPricingData.formulaComponents,
        formulaMetadata
      ),
      ContractDifferential: indexPricingData.FormulaDifferential ?? 0,
      Formula: formula,
      StartDate: constructDateTimeString(values.VisibilityWindowStartDate, values.VisibilityWindowStartTime),
      EndDate: constructDateTimeString(values.VisibilityWindowEndDate, values.VisibilityWindowEndTime),
      InternalFormulaDisplayNameOverride: indexPricingData.InternalDisplayName || undefined,
      ExternalFormulaDisplayNameOverride: indexPricingData.ExternalDisplayName || undefined,
    }
  }

  return {
    SpecialOfferTemplateId: values.SpecialOfferTemplateId,
    MinimumVolumePerOrder: values.MinimumVolumePerOrder,
    MaximumVolumePerOrder: values.MaximumVolumePerOrder,
    VolumeIncrement: values.VolumeIncrement,
    TotalVolume: values.TotalVolume,
    ReservePrice: indexPricingData?.ReservePrice ?? values.ReservePrice ?? undefined,
    FixedPrice: values.ReservePrice || undefined,
    VisibilityStartDateTime: constructDateTimeString(
      values.VisibilityWindowStartDate,
      values.VisibilityWindowStartTime
    ),
    VisibilityEndDateTime: constructDateTimeString(values.VisibilityWindowEndDate, values.VisibilityWindowEndTime),
    OrderEffectiveStartDateTime: constructDateTimeString(values.PickupWindowStartDate, values.PickupWindowStartTime),
    OrderEffectiveEndDateTime: constructDateTimeString(values.PickupWindowEndDate, values.PickupWindowEndTime),
    CounterPartyIds: values.CounterPartyIds,
    TradeEntrySetupIds: tradeEntrySetupIds,
    InvitationTriggerDateTimeTZ,
    IndexPricingInfo: indexPricingInfo,
  }
}

export function constructDateTimeString(date: Dayjs, time?: Dayjs): string {
  return dayjs(date)
    .hour(time ? time.hour() : 0)
    .minute(time ? time.minute() : 0)
    .second(0)
    .format(dateFormat.ISO)
}

export function constructDateTime(date: Dayjs, time?: Dayjs): Date {
  return dayjs(date)
    .hour(time ? time.hour() : 0)
    .minute(time ? time.minute() : 0)
    .second(0)
    .toDate()
}

export function validateFormFields({
  form,
  goNext,
  currentStep,
  setShowIndexError,
  isIndexPricing,
}: {
  form: FormInstance
  goNext: () => void
  currentStep: number
  setShowIndexError: React.Dispatch<React.SetStateAction<boolean>>
  isIndexPricing: boolean
}) {
  const fieldsToValidate = isIndexPricing ? step1Fields.concat('IndexPrice') : step1Fields
  if (currentStep === 1) {
    form
      .validateFields(['ProductLocation'])
      .then(() => {
        form
          .validateFields(fieldsToValidate)
          .then(() => {
            setShowIndexError(false)
            goNext()
          })
          .catch(({ errorFields }: any) => {
            if (errorFields?.length && isIndexPricing) {
              setShowIndexError(errorFields?.find((f: any) => f.name[0] === 'IndexPrice')?.errors?.length > 0)
            }
          })
      })
      .catch(() => {})
  }
  if (currentStep === 2) {
    form.validateFields(step2Fields).then(() => goNext())
  }
}
