// Bakery products data for BakeryDemo
export const bakeryProducts = [
  {
    "ProductId": "BR001",
    "Name": "Classic Sourdough",
    "Description": "Traditional artisan sourdough with a crispy crust and tangy flavor",
    "Category": "Breads",
    "BaseCost": 2.50,
    "IngredientsCost": 1.20,
    "PricingFormula": "base_cost * 1.4 + ingredients_cost * 1.1",
    "FormulaNote": "Standard markup for daily bread with minimal ingredient markup",
    "FinalPrice": 4.82,
    "IsAvailable": true
  },
  {
    "ProductId": "BR002",
    "Name": "Multigrain Artisan",
    "Description": "Hearty blend of seven grains with sunflower seeds",
    "Category": "Breads",
    "BaseCost": 3.00,
    "IngredientsCost": 2.10,
    "PricingFormula": "base_cost * 1.5 + ingredients_cost * 1.3",
    "FormulaNote": "Premium pricing for specialty grains and seeds",
    "FinalPrice": 7.23,
    "IsAvailable": true
  },
  {
    "ProductId": "PA001",
    "Name": "Chocolate Croissant",
    "Description": "Flaky buttery pastry filled with premium dark chocolate",
    "Category": "Pastries",
    "BaseCost": 1.80,
    "IngredientsCost": 0.95,
    "PricingFormula": "base_cost * 2.2 + ingredients_cost * 1.8",
    "FormulaNote": "High markup for labor-intensive pastry work",
    "FinalPrice": 5.67,
    "IsAvailable": true
  },
  {
    "ProductId": "PA002",
    "Name": "Almond Danish",
    "Description": "Delicate pastry topped with sliced almonds and cream filling",
    "Category": "Pastries",
    "BaseCost": 2.10,
    "IngredientsCost": 1.40,
    "PricingFormula": "base_cost * 1.9 + ingredients_cost * 1.6",
    "FormulaNote": "Moderate premium for nut-based pastries",
    "FinalPrice": 6.23,
    "IsAvailable": false
  },
  {
    "ProductId": "CK001",
    "Name": "Red Velvet Cupcake",
    "Description": "Moist red velvet cake with cream cheese frosting",
    "Category": "Cakes",
    "BaseCost": 1.50,
    "IngredientsCost": 0.85,
    "PricingFormula": "(base_cost + ingredients_cost) * 2.5",
    "FormulaNote": "Simple doubling plus premium for decorated items",
    "FinalPrice": 5.88,
    "IsAvailable": true
  },
  {
    "ProductId": "CK002",
    "Name": "Lemon Drizzle Slice",
    "Description": "Zesty lemon sponge with tangy glaze",
    "Category": "Cakes",
    "BaseCost": 1.20,
    "IngredientsCost": 0.60,
    "PricingFormula": "base_cost * 2.0 + ingredients_cost * 2.2",
    "FormulaNote": "Higher ingredient markup for fresh citrus",
    "FinalPrice": 3.72,
    "IsAvailable": true
  },
  {
    "ProductId": "CK003",
    "Name": "Custom Wedding Cake",
    "Description": "Three-tier vanilla sponge with buttercream roses",
    "Category": "Cakes",
    "BaseCost": 45.00,
    "IngredientsCost": 25.00,
    "PricingFormula": "base_cost * 1.2 + ingredients_cost * 1.1 + 150",
    "FormulaNote": "Custom work fee plus materials and labor",
    "FinalPrice": 231.50,
    "IsAvailable": true
  },
  {
    "ProductId": "CO001",
    "Name": "Chocolate Chip Cookie",
    "Description": "Classic cookie with premium Belgian chocolate chips",
    "Category": "Cookies",
    "BaseCost": 0.45,
    "IngredientsCost": 0.30,
    "PricingFormula": "(base_cost + ingredients_cost) * 3.5",
    "FormulaNote": "High volume margin for popular item",
    "FinalPrice": 2.63,
    "IsAvailable": true
  },
  {
    "ProductId": "CO002",
    "Name": "Oatmeal Raisin Cookie",
    "Description": "Chewy oatmeal cookie with plump California raisins",
    "Category": "Cookies",
    "BaseCost": 0.40,
    "IngredientsCost": 0.25,
    "PricingFormula": "base_cost * 3.2 + ingredients_cost * 3.8",
    "FormulaNote": "Dried fruit premium pricing",
    "FinalPrice": 2.23,
    "IsAvailable": true
  },
  {
    "ProductId": "CO003",
    "Name": "Macarons (6-pack)",
    "Description": "Assorted French macarons with ganache filling",
    "Category": "Cookies",
    "BaseCost": 4.20,
    "IngredientsCost": 2.80,
    "PricingFormula": "base_cost * 1.8 + ingredients_cost * 2.5 + 3",
    "FormulaNote": "Skill premium for technical French pastry",
    "FinalPrice": 17.56,
    "IsAvailable": true
  },
  {
    "ProductId": "MU001",
    "Name": "Blueberry Muffin",
    "Description": "Fluffy muffin bursting with fresh Maine blueberries",
    "Category": "Muffins",
    "BaseCost": 0.80,
    "IngredientsCost": 0.65,
    "PricingFormula": "base_cost * 2.1 + ingredients_cost * 1.9",
    "FormulaNote": "Fresh berry premium with standard markup",
    "FinalPrice": 2.92,
    "IsAvailable": true
  },
  {
    "ProductId": "MU002",
    "Name": "Double Chocolate Muffin",
    "Description": "Rich chocolate muffin with chocolate chips",
    "Category": "Muffins",
    "BaseCost": 0.85,
    "IngredientsCost": 0.70,
    "PricingFormula": "(base_cost + ingredients_cost) * 2.3",
    "FormulaNote": "Indulgent item pricing for chocolate lovers",
    "FinalPrice": 3.57,
    "IsAvailable": true
  },
  {
    "ProductId": "MU003",
    "Name": "Banana Nut Muffin",
    "Description": "Moist banana muffin with toasted walnuts",
    "Category": "Muffins",
    "BaseCost": 0.75,
    "IngredientsCost": 0.55,
    "PricingFormula": "base_cost * 2.0 + ingredients_cost * 2.4",
    "FormulaNote": "Nut cost adjustment with standard base markup",
    "FinalPrice": 2.82,
    "IsAvailable": false
  },
  {
    "ProductId": "PA003",
    "Name": "Apple Turnover",
    "Description": "Flaky pastry filled with cinnamon spiced apples",
    "Category": "Pastries",
    "BaseCost": 1.60,
    "IngredientsCost": 0.90,
    "PricingFormula": "base_cost * 1.7 + ingredients_cost * 1.5 + 0.5",
    "FormulaNote": "Seasonal fruit adjustment plus handling fee",
    "FinalPrice": 4.57,
    "IsAvailable": true
  },
  {
    "ProductId": "BR003",
    "Name": "Focaccia Bread",
    "Description": "Italian flatbread with rosemary and sea salt",
    "Category": "Breads",
    "BaseCost": 2.20,
    "IngredientsCost": 1.10,
    "PricingFormula": "base_cost * 1.6 + ingredients_cost * 1.4",
    "FormulaNote": "Herb and specialty salt premium",
    "FinalPrice": 5.06,
    "IsAvailable": true
  },
  {
    "ProductId": "CK004",
    "Name": "Carrot Cake Slice",
    "Description": "Spiced carrot cake with cream cheese frosting and walnuts",
    "Category": "Cakes",
    "BaseCost": 1.80,
    "IngredientsCost": 1.20,
    "PricingFormula": "base_cost * 1.8 + ingredients_cost * 2.1 + 1",
    "FormulaNote": "Vegetable cake complexity plus nut garnish fee",
    "FinalPrice": 6.76,
    "IsAvailable": true
  },
  {
    "ProductId": "PA004",
    "Name": "Cinnamon Roll",
    "Description": "Soft spiral pastry with cinnamon sugar and cream glaze",
    "Category": "Pastries",
    "BaseCost": 1.40,
    "IngredientsCost": 0.80,
    "PricingFormula": "(base_cost + ingredients_cost) * 2.4",
    "FormulaNote": "Popular breakfast item with comfort food markup",
    "FinalPrice": 5.28,
    "IsAvailable": true
  },
  {
    "ProductId": "CO004",
    "Name": "Snickerdoodle Cookie",
    "Description": "Soft cookie rolled in cinnamon sugar",
    "Category": "Cookies",
    "BaseCost": 0.35,
    "IngredientsCost": 0.20,
    "PricingFormula": "base_cost * 4.0 + ingredients_cost * 3.0",
    "FormulaNote": "High margin for simple but popular cookie",
    "FinalPrice": 2.00,
    "IsAvailable": true
  },
  {
    "ProductId": "BR004",
    "Name": "Challah Bread",
    "Description": "Traditional braided egg bread with sesame seeds",
    "Category": "Breads",
    "BaseCost": 3.20,
    "IngredientsCost": 1.80,
    "PricingFormula": "base_cost * 1.3 + ingredients_cost * 1.6 + 2",
    "FormulaNote": "Egg enrichment cost plus braiding labor premium",
    "FinalPrice": 8.04,
    "IsAvailable": true
  },
  {
    "ProductId": "CK005",
    "Name": "Tiramisu Slice",
    "Description": "Classic Italian dessert with mascarpone and coffee",
    "Category": "Cakes",
    "BaseCost": 2.80,
    "IngredientsCost": 2.20,
    "PricingFormula": "base_cost * 1.4 + ingredients_cost * 1.8 + 2.5",
    "FormulaNote": "Premium Italian dessert with imported ingredient surcharge",
    "FinalPrice": 10.38,
    "IsAvailable": true
  }
];