// Mock data for ProductGrid demo
export const mockData = [
  {
    "ProductId": 1,
    "Name": "Product A",
    "Abbreviation": "PRD001",
    "Commodity": "Diesel",
    "Grade": "#2",
    "Price": 7.25,
    "volumeAvailable": 15750,
    "IsActive": true,
    "ProductGroup": "Distillates",
    "CreatedDateTime": "2025-04-08T05:56:29.882Z"
  },
  {
    "ProductId": 2,
    "Name": "Product B",
    "Abbreviation": "PRD002",
    "Commodity": "Heating Oil",
    "Grade": "Premium",
    "Price": 3.45,
    "volumeAvailable": 22300,
    "IsActive": true,
    "ProductGroup": "Chemicals",
    "CreatedDateTime": "2025-03-14T05:52:08.439Z"
  },
  {
    "ProductId": 3,
    "Name": "Product C",
    "Abbreviation": "PRD003",
    "Commodity": "Gasoline",
    "Grade": "87 Octane",
    "Price": 8.92,
    "volumeAvailable": 8950,
    "IsActive": true,
    "ProductGroup": "Motor Fuels",
    "CreatedDateTime": "2025-06-19T01:16:29.586Z"
  },
  {
    "ProductId": 4,
    "Name": "Product D",
    "Abbreviation": "PRD004",
    "Commodity": "Diesel",
    "Grade": "#2",
    "Price": 5.67,
    "volumeAvailable": 31200,
    "IsActive": true,
    "ProductGroup": "Distillates",
    "CreatedDateTime": "2025-08-22T17:17:37.371Z"
  },
  {
    "ProductId": 5,
    "Name": "Product E",
    "Abbreviation": "PRD005",
    "Commodity": "Heating Oil",
    "Grade": "Premium",
    "Price": 2.18,
    "volumeAvailable": 18750,
    "IsActive": true,
    "ProductGroup": "Chemicals",
    "CreatedDateTime": "2024-12-28T09:25:35.899Z"
  },
  {
    "ProductId": 6,
    "Name": "Product F",
    "Abbreviation": "PRD006",
    "Commodity": "Gasoline",
    "Grade": "87 Octane",
    "Price": 9.33,
    "IsActive": true,
    "ProductGroup": "Motor Fuels",
    "CreatedDateTime": "2025-07-05T23:24:35.086Z"
  },
  {
    "ProductId": 7,
    "Name": "Product G",
    "Abbreviation": "PRD007",
    "Commodity": "Diesel",
    "Grade": "#2",
    "Price": 4.75,
    "IsActive": false,
    "ProductGroup": "Distillates",
    "CreatedDateTime": "2025-02-12T18:08:44.578Z"
  },
  {
    "ProductId": 8,
    "Name": "Product H",
    "Abbreviation": "PRD008",
    "Commodity": "Heating Oil",
    "Grade": "Premium",
    "Price": 6.89,
    "IsActive": true,
    "ProductGroup": "Chemicals",
    "CreatedDateTime": "2025-06-14T21:08:49.234Z"
  },
  {
    "ProductId": 9,
    "Name": "Product I",
    "Abbreviation": "PRD009",
    "Commodity": "Gasoline",
    "Grade": "87 Octane",
    "Price": 1.52,
    "IsActive": true,
    "ProductGroup": "Motor Fuels",
    "CreatedDateTime": "2024-11-29T06:11:37.810Z"
  },
  {
    "ProductId": 10,
    "Name": "Product J",
    "Abbreviation": "PRD010",
    "Commodity": "Diesel",
    "Grade": "#2",
    "Price": 8.14,
    "IsActive": true,
    "ProductGroup": "Distillates",
    "CreatedDateTime": "2025-05-27T00:53:31.258Z"
  },
  {
    "ProductId": 11,
    "Name": "Product K",
    "Abbreviation": "PRD011",
    "Commodity": "Heating Oil",
    "Grade": "Premium",
    "Price": 3.91,
    "IsActive": true,
    "ProductGroup": "Chemicals",
    "CreatedDateTime": "2025-07-16T18:40:20.762Z"
  },
  {
    "ProductId": 12,
    "Name": "Product L",
    "Abbreviation": "PRD012",
    "Commodity": "Gasoline",
    "Grade": "87 Octane",
    "Price": 7.63,
    "IsActive": true,
    "ProductGroup": "Motor Fuels",
    "CreatedDateTime": "2024-11-28T19:29:05.539Z"
  },
  {
    "ProductId": 13,
    "Name": "Product M",
    "Abbreviation": "PRD013",
    "Commodity": "Diesel",
    "Grade": "#2",
    "Price": 5.28,
    "IsActive": true,
    "ProductGroup": "Distillates",
    "CreatedDateTime": "2025-04-23T02:26:39.484Z"
  },
  {
    "ProductId": 14,
    "Name": "Product N",
    "Abbreviation": "PRD014",
    "Commodity": "Heating Oil",
    "Grade": "Premium",
    "Price": 9.05,
    "IsActive": false,
    "ProductGroup": "Chemicals",
    "CreatedDateTime": "2024-12-09T21:15:21.415Z"
  },
  {
    "ProductId": 15,
    "Name": "Product O",
    "Abbreviation": "PRD015",
    "Commodity": "Gasoline",
    "Grade": "87 Octane",
    "Price": 2.76,
    "IsActive": true,
    "ProductGroup": "Motor Fuels",
    "CreatedDateTime": "2024-10-07T18:16:43.663Z"
  },
  {
    "ProductId": 16,
    "Name": "Product P",
    "Abbreviation": "PRD016",
    "Commodity": "Diesel",
    "Grade": "#2",
    "Price": 6.41,
    "IsActive": false,
    "ProductGroup": "Distillates",
    "CreatedDateTime": "2025-06-20T05:02:02.527Z"
  },
  {
    "ProductId": 17,
    "Name": "Product Q",
    "Abbreviation": "PRD017",
    "Commodity": "Heating Oil",
    "Grade": "Premium",
    "Price": 4.32,
    "IsActive": true,
    "ProductGroup": "Chemicals",
    "CreatedDateTime": "2024-12-16T12:57:15.168Z"
  },
  {
    "ProductId": 18,
    "Name": "Product R",
    "Abbreviation": "PRD018",
    "Commodity": "Gasoline",
    "Grade": "87 Octane",
    "Price": 8.57,
    "IsActive": true,
    "ProductGroup": "Motor Fuels",
    "CreatedDateTime": "2024-12-14T16:35:26.656Z"
  },
  {
    "ProductId": 19,
    "Name": "Product S",
    "Abbreviation": "PRD019",
    "Commodity": "Diesel",
    "Grade": "#2",
    "Price": 1.89,
    "IsActive": true,
    "ProductGroup": "Distillates",
    "CreatedDateTime": "2025-05-06T16:36:32.833Z"
  },
  {
    "ProductId": 20,
    "Name": "Product T",
    "Abbreviation": "PRD020",
    "Commodity": "Heating Oil",
    "Grade": "Premium",
    "Price": 7.98,
    "IsActive": false,
    "ProductGroup": "Chemicals",
    "CreatedDateTime": "2025-04-25T01:29:46.609Z"
  },
  {
    "ProductId": 21,
    "Name": "Product U",
    "Abbreviation": "PRD021",
    "Commodity": "Gasoline",
    "Grade": "87 Octane",
    "Price": 3.64,
    "IsActive": true,
    "ProductGroup": "Motor Fuels",
    "CreatedDateTime": "2025-08-20T08:37:21.016Z"
  },
  {
    "ProductId": 22,
    "Name": "Product V",
    "Abbreviation": "PRD022",
    "Commodity": "Diesel",
    "Grade": "#2",
    "Price": 5.93,
    "IsActive": true,
    "ProductGroup": "Distillates",
    "CreatedDateTime": "2024-10-29T14:55:00.745Z"
  },
  {
    "ProductId": 23,
    "Name": "Product W",
    "Abbreviation": "PRD023",
    "Commodity": "Heating Oil",
    "Grade": "Premium",
    "Price": 9.21,
    "IsActive": false,
    "ProductGroup": "Chemicals",
    "CreatedDateTime": "2025-08-25T13:43:08.523Z"
  },
  {
    "ProductId": 24,
    "Name": "Product X",
    "Abbreviation": "PRD024",
    "Commodity": "Gasoline",
    "Grade": "87 Octane",
    "Price": 4.17,
    "IsActive": true,
    "ProductGroup": "Motor Fuels",
    "CreatedDateTime": "2025-05-01T21:25:18.907Z"
  },
  {
    "ProductId": 25,
    "Name": "Product Y",
    "Abbreviation": "PRD025",
    "Commodity": "Diesel",
    "Grade": "#2",
    "Price": 6.72,
    "IsActive": true,
    "ProductGroup": "Distillates",
    "CreatedDateTime": "2025-05-10T20:58:08.125Z"
  }
];