export type PriceExceptionRow = {
  id: number
  configurationName: string
  product: string
  location: string
  costType: string

  margin_hardLow: number | null
  margin_softLow: number | null
  margin_softHigh: number | null
  margin_hardHigh: number | null

  cost_hardLow: number | null
  cost_softLow: number | null
  cost_softHigh: number | null
  cost_hardHigh: number | null

  marketMove_hardLow: number | null
  marketMove_softLow: number | null
  marketMove_softHigh: number | null
  marketMove_hardHigh: number | null

  priceDelta_hardLow: number | null
  priceDelta_softLow: number | null
  priceDelta_softHigh: number | null
  priceDelta_hardHigh: number | null

  price_hardLow: number | null
  price_softLow: number | null
  price_softHigh: number | null
  price_hardHigh: number | null

  benchDelta_hardLow: number | null
  benchDelta_softLow: number | null
  benchDelta_softHigh: number | null
  benchDelta_hardHigh: number | null

  benchValue_hardLow: number | null
  benchValue_softLow: number | null
  benchValue_softHigh: number | null
  benchValue_hardHigh: number | null
}

export const priceExceptionData: PriceExceptionRow[] = [
  // Wholesale Config (5 rows)
  {
    id: 1,
    configurationName: 'Wholesale Config',
    product: 'Diesel #2',
    location: 'Houston Term.',
    costType: 'Contract',
    margin_hardLow: -0.0500,
    margin_softLow: -0.0200,
    margin_softHigh: 0.1500,
    margin_hardHigh: 0.2500,
    cost_hardLow: 1.5000,
    cost_softLow: 1.8000,
    cost_softHigh: 2.8000,
    cost_hardHigh: 3.2000,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0500,
    marketMove_hardHigh: 0.1000,
    priceDelta_hardLow: -0.1500,
    priceDelta_softLow: -0.0800,
    priceDelta_softHigh: 0.0800,
    priceDelta_hardHigh: 0.1500,
    price_hardLow: 1.8000,
    price_softLow: 2.0000,
    price_softHigh: 3.2000,
    price_hardHigh: 3.5000,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: 0.0400,
    benchDelta_hardHigh: 0.0800,
    benchValue_hardLow: 1.6000,
    benchValue_softLow: 1.8000,
    benchValue_softHigh: 2.9000,
    benchValue_hardHigh: 3.3000,
  },
  {
    id: 2,
    configurationName: 'Wholesale Config',
    product: 'Unleaded 87',
    location: 'Dallas Hub',
    costType: 'Instrument',
    margin_hardLow: -0.0400,
    margin_softLow: -0.0100,
    margin_softHigh: 0.1200,
    margin_hardHigh: 0.2000,
    cost_hardLow: 1.6000,
    cost_softLow: 1.9000,
    cost_softHigh: 2.7000,
    cost_hardHigh: 3.0000,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0400,
    marketMove_hardHigh: 0.0800,
    priceDelta_hardLow: -0.1200,
    priceDelta_softLow: -0.0600,
    priceDelta_softHigh: 0.0600,
    priceDelta_hardHigh: 0.1200,
    price_hardLow: 1.9000,
    price_softLow: 2.1000,
    price_softHigh: 3.0000,
    price_hardHigh: 3.3000,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: 0.0350,
    benchDelta_hardHigh: 0.0700,
    benchValue_hardLow: 1.7000,
    benchValue_softLow: 1.9000,
    benchValue_softHigh: 2.8000,
    benchValue_hardHigh: 3.1000,
  },
  {
    id: 3,
    configurationName: 'Wholesale Config',
    product: 'Premium 91',
    location: 'Chicago Term.',
    costType: 'Marker',
    margin_hardLow: -0.0300,
    margin_softLow: -0.0100,
    margin_softHigh: 0.1000,
    margin_hardHigh: 0.1800,
    cost_hardLow: null,
    cost_softLow: null,
    cost_softHigh: null,
    cost_hardHigh: null,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: null,
    marketMove_hardHigh: null,
    priceDelta_hardLow: null,
    priceDelta_softLow: null,
    priceDelta_softHigh: null,
    priceDelta_hardHigh: null,
    price_hardLow: null,
    price_softLow: null,
    price_softHigh: null,
    price_hardHigh: null,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: null,
    benchDelta_hardHigh: null,
    benchValue_hardLow: null,
    benchValue_softLow: null,
    benchValue_softHigh: null,
    benchValue_hardHigh: null,
  },
  {
    id: 4,
    configurationName: 'Wholesale Config',
    product: 'Diesel #2',
    location: 'Houston Term.',
    costType: 'Contract',
    margin_hardLow: -0.0600,
    margin_softLow: -0.0250,
    margin_softHigh: 0.1600,
    margin_hardHigh: 0.2800,
    cost_hardLow: 1.4500,
    cost_softLow: 1.7500,
    cost_softHigh: 2.9000,
    cost_hardHigh: 3.3000,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0600,
    marketMove_hardHigh: 0.1200,
    priceDelta_hardLow: -0.1800,
    priceDelta_softLow: -0.0900,
    priceDelta_softHigh: 0.0900,
    priceDelta_hardHigh: 0.1800,
    price_hardLow: 1.7500,
    price_softLow: 1.9500,
    price_softHigh: 3.3000,
    price_hardHigh: 3.6000,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: 0.0450,
    benchDelta_hardHigh: 0.0900,
    benchValue_hardLow: 1.5500,
    benchValue_softLow: 1.7500,
    benchValue_softHigh: 3.0000,
    benchValue_hardHigh: 3.4000,
  },
  {
    id: 5,
    configurationName: 'Wholesale Config',
    product: 'Unleaded 87',
    location: 'Dallas Hub',
    costType: 'Instrument',
    margin_hardLow: -0.0450,
    margin_softLow: -0.0150,
    margin_softHigh: 0.1300,
    margin_hardHigh: 0.2200,
    cost_hardLow: 1.5500,
    cost_softLow: 1.8500,
    cost_softHigh: 2.7500,
    cost_hardHigh: 3.1000,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0450,
    marketMove_hardHigh: 0.0900,
    priceDelta_hardLow: -0.1300,
    priceDelta_softLow: -0.0700,
    priceDelta_softHigh: 0.0700,
    priceDelta_hardHigh: 0.1300,
    price_hardLow: 1.8500,
    price_softLow: 2.0500,
    price_softHigh: 3.1000,
    price_hardHigh: 3.4000,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: 0.0380,
    benchDelta_hardHigh: 0.0750,
    benchValue_hardLow: 1.6500,
    benchValue_softLow: 1.8500,
    benchValue_softHigh: 2.8500,
    benchValue_hardHigh: 3.2000,
  },
  // Industrial Config (5 rows)
  {
    id: 6,
    configurationName: 'Industrial Config',
    product: 'Diesel #2',
    location: 'Chicago Term.',
    costType: 'Contract',
    margin_hardLow: -0.0350,
    margin_softLow: -0.0100,
    margin_softHigh: 0.1100,
    margin_hardHigh: 0.1900,
    cost_hardLow: 1.7000,
    cost_softLow: 2.0000,
    cost_softHigh: 2.6000,
    cost_hardHigh: 2.9000,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0350,
    marketMove_hardHigh: 0.0700,
    priceDelta_hardLow: -0.1000,
    priceDelta_softLow: -0.0500,
    priceDelta_softHigh: 0.0500,
    priceDelta_hardHigh: 0.1000,
    price_hardLow: 2.0000,
    price_softLow: 2.2000,
    price_softHigh: 2.9000,
    price_hardHigh: 3.2000,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: 0.0300,
    benchDelta_hardHigh: 0.0600,
    benchValue_hardLow: 1.8000,
    benchValue_softLow: 2.0000,
    benchValue_softHigh: 2.7000,
    benchValue_hardHigh: 3.0000,
  },
  {
    id: 7,
    configurationName: 'Industrial Config',
    product: 'Premium 91',
    location: 'Houston Term.',
    costType: 'Marker',
    margin_hardLow: -0.0400,
    margin_softLow: -0.0150,
    margin_softHigh: 0.1400,
    margin_hardHigh: 0.2400,
    cost_hardLow: null,
    cost_softLow: null,
    cost_softHigh: null,
    cost_hardHigh: null,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0500,
    marketMove_hardHigh: 0.1000,
    priceDelta_hardLow: null,
    priceDelta_softLow: null,
    priceDelta_softHigh: null,
    priceDelta_hardHigh: null,
    price_hardLow: null,
    price_softLow: null,
    price_softHigh: null,
    price_hardHigh: null,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: null,
    benchDelta_hardHigh: null,
    benchValue_hardLow: null,
    benchValue_softLow: null,
    benchValue_softHigh: null,
    benchValue_hardHigh: null,
  },
  {
    id: 8,
    configurationName: 'Industrial Config',
    product: 'Unleaded 87',
    location: 'Dallas Hub',
    costType: 'Instrument',
    margin_hardLow: -0.0500,
    margin_softLow: -0.0200,
    margin_softHigh: 0.1500,
    margin_hardHigh: 0.2500,
    cost_hardLow: 1.5500,
    cost_softLow: 1.8500,
    cost_softHigh: 2.8500,
    cost_hardHigh: 3.2500,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0550,
    marketMove_hardHigh: 0.1100,
    priceDelta_hardLow: -0.1400,
    priceDelta_softLow: -0.0700,
    priceDelta_softHigh: 0.0700,
    priceDelta_hardHigh: 0.1400,
    price_hardLow: 1.8500,
    price_softLow: 2.0500,
    price_softHigh: 3.1500,
    price_hardHigh: 3.4500,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: 0.0400,
    benchDelta_hardHigh: 0.0800,
    benchValue_hardLow: 1.6500,
    benchValue_softLow: 1.8500,
    benchValue_softHigh: 2.9500,
    benchValue_hardHigh: 3.3500,
  },
  {
    id: 9,
    configurationName: 'Industrial Config',
    product: 'Diesel #2',
    location: 'Chicago Term.',
    costType: 'Contract',
    margin_hardLow: -0.0300,
    margin_softLow: -0.0100,
    margin_softHigh: 0.1000,
    margin_hardHigh: 0.1800,
    cost_hardLow: 1.6500,
    cost_softLow: 1.9500,
    cost_softHigh: 2.6500,
    cost_hardHigh: 2.9500,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0400,
    marketMove_hardHigh: 0.0800,
    priceDelta_hardLow: -0.1100,
    priceDelta_softLow: -0.0550,
    priceDelta_softHigh: 0.0550,
    priceDelta_hardHigh: 0.1100,
    price_hardLow: 1.9500,
    price_softLow: 2.1500,
    price_softHigh: 2.9500,
    price_hardHigh: 3.2500,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: 0.0350,
    benchDelta_hardHigh: 0.0700,
    benchValue_hardLow: 1.7500,
    benchValue_softLow: 1.9500,
    benchValue_softHigh: 2.7500,
    benchValue_hardHigh: 3.0500,
  },
  {
    id: 10,
    configurationName: 'Industrial Config',
    product: 'Premium 91',
    location: 'Houston Term.',
    costType: 'Marker',
    margin_hardLow: -0.0550,
    margin_softLow: -0.0200,
    margin_softHigh: 0.1600,
    margin_hardHigh: 0.2600,
    cost_hardLow: 1.7500,
    cost_softLow: 2.0500,
    cost_softHigh: 2.8500,
    cost_hardHigh: 3.1500,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0500,
    marketMove_hardHigh: 0.1000,
    priceDelta_hardLow: -0.1600,
    priceDelta_softLow: -0.0800,
    priceDelta_softHigh: 0.0800,
    priceDelta_hardHigh: 0.1600,
    price_hardLow: 2.0500,
    price_softLow: 2.2500,
    price_softHigh: 3.1500,
    price_hardHigh: 3.4500,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: 0.0450,
    benchDelta_hardHigh: 0.0900,
    benchValue_hardLow: 1.8500,
    benchValue_softLow: 2.0500,
    benchValue_softHigh: 2.9500,
    benchValue_hardHigh: 3.2500,
  },
  // Retail Config (5 rows)
  {
    id: 11,
    configurationName: 'Retail Config',
    product: 'Unleaded 87',
    location: 'Dallas Hub',
    costType: 'Instrument',
    margin_hardLow: -0.0400,
    margin_softLow: -0.0150,
    margin_softHigh: 0.1200,
    margin_hardHigh: 0.2000,
    cost_hardLow: 1.6000,
    cost_softLow: 1.9000,
    cost_softHigh: 2.7000,
    cost_hardHigh: 3.0000,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0400,
    marketMove_hardHigh: 0.0800,
    priceDelta_hardLow: -0.1200,
    priceDelta_softLow: -0.0600,
    priceDelta_softHigh: 0.0600,
    priceDelta_hardHigh: 0.1200,
    price_hardLow: 1.9000,
    price_softLow: 2.1000,
    price_softHigh: 3.0000,
    price_hardHigh: 3.3000,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: 0.0350,
    benchDelta_hardHigh: 0.0700,
    benchValue_hardLow: 1.7000,
    benchValue_softLow: 1.9000,
    benchValue_softHigh: 2.8000,
    benchValue_hardHigh: 3.1000,
  },
  {
    id: 12,
    configurationName: 'Retail Config',
    product: 'Diesel #2',
    location: 'Houston Term.',
    costType: 'Contract',
    margin_hardLow: -0.0350,
    margin_softLow: -0.0100,
    margin_softHigh: 0.1100,
    margin_hardHigh: 0.1900,
    cost_hardLow: 1.5000,
    cost_softLow: 1.8000,
    cost_softHigh: 2.8000,
    cost_hardHigh: 3.2000,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0450,
    marketMove_hardHigh: 0.0900,
    priceDelta_hardLow: -0.1300,
    priceDelta_softLow: -0.0650,
    priceDelta_softHigh: 0.0650,
    priceDelta_hardHigh: 0.1300,
    price_hardLow: 1.8000,
    price_softLow: 2.0000,
    price_softHigh: 3.2000,
    price_hardHigh: 3.5000,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: 0.0400,
    benchDelta_hardHigh: 0.0800,
    benchValue_hardLow: 1.6000,
    benchValue_softLow: 1.8000,
    benchValue_softHigh: 2.9000,
    benchValue_hardHigh: 3.3000,
  },
  {
    id: 13,
    configurationName: 'Retail Config',
    product: 'Premium 91',
    location: 'Chicago Term.',
    costType: 'Marker',
    margin_hardLow: null,
    margin_softLow: null,
    margin_softHigh: null,
    margin_hardHigh: null,
    cost_hardLow: null,
    cost_softLow: null,
    cost_softHigh: null,
    cost_hardHigh: null,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: null,
    marketMove_hardHigh: null,
    priceDelta_hardLow: null,
    priceDelta_softLow: null,
    priceDelta_softHigh: null,
    priceDelta_hardHigh: null,
    price_hardLow: null,
    price_softLow: null,
    price_softHigh: null,
    price_hardHigh: null,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: null,
    benchDelta_hardHigh: null,
    benchValue_hardLow: null,
    benchValue_softLow: null,
    benchValue_softHigh: null,
    benchValue_hardHigh: null,
  },
  {
    id: 14,
    configurationName: 'Retail Config',
    product: 'Unleaded 87',
    location: 'Dallas Hub',
    costType: 'Instrument',
    margin_hardLow: -0.0450,
    margin_softLow: -0.0150,
    margin_softHigh: 0.1300,
    margin_hardHigh: 0.2200,
    cost_hardLow: 1.5500,
    cost_softLow: 1.8500,
    cost_softHigh: 2.7500,
    cost_hardHigh: 3.1000,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0500,
    marketMove_hardHigh: 0.1000,
    priceDelta_hardLow: -0.1400,
    priceDelta_softLow: -0.0700,
    priceDelta_softHigh: 0.0700,
    priceDelta_hardHigh: 0.1400,
    price_hardLow: 1.8500,
    price_softLow: 2.0500,
    price_softHigh: 3.1000,
    price_hardHigh: 3.4000,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: 0.0380,
    benchDelta_hardHigh: 0.0750,
    benchValue_hardLow: 1.6500,
    benchValue_softLow: 1.8500,
    benchValue_softHigh: 2.8500,
    benchValue_hardHigh: 3.2000,
  },
  {
    id: 15,
    configurationName: 'Retail Config',
    product: 'Diesel #2',
    location: 'Houston Term.',
    costType: 'Contract',
    margin_hardLow: -0.0500,
    margin_softLow: -0.0200,
    margin_softHigh: 0.1500,
    margin_hardHigh: 0.2500,
    cost_hardLow: 1.4500,
    cost_softLow: 1.7500,
    cost_softHigh: 2.9000,
    cost_hardHigh: 3.3000,
    marketMove_hardLow: null,
    marketMove_softLow: null,
    marketMove_softHigh: 0.0550,
    marketMove_hardHigh: 0.1100,
    priceDelta_hardLow: -0.1500,
    priceDelta_softLow: -0.0800,
    priceDelta_softHigh: 0.0800,
    priceDelta_hardHigh: 0.1500,
    price_hardLow: 1.7500,
    price_softLow: 1.9500,
    price_softHigh: 3.3000,
    price_hardHigh: 3.6000,
    benchDelta_hardLow: null,
    benchDelta_softLow: null,
    benchDelta_softHigh: 0.0450,
    benchDelta_hardHigh: 0.0900,
    benchValue_hardLow: 1.5500,
    benchValue_softLow: 1.7500,
    benchValue_softHigh: 3.0000,
    benchValue_hardHigh: 3.4000,
  },
]
