// Sample data for Subscription Management demo
// Based on Reece's mockups and Gravitate ManagePriceNotifications patterns

import {
  SubscriptionData,
  RecipientData,
  DEFAULT_CONTENT_CONFIG,
} from './SubscriptionManagement.types';

// Sample subscription data matching mockup patterns
export const sampleSubscriptionData: SubscriptionData[] = [
  {
    Id: 1,
    CounterPartyId: 1104546,
    CounterPartyName: '284 FUEL SUPPLY LLC - 1104546',
    QuoteConfigurationName: 'Branded Rack Prices',
    ProductIds: Array.from({ length: 116 }, (_, i) => i + 1),
    LocationIds: [1, 2, 3, 4],
    IsActive: true,
    IncludeCounterparty: true,
    IncludeLoadingNumber: true,
    IncludePortalLink: true,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: true,
    IncludeExpirationDate: false,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: false,
    IncludeProductPrice: true,
    IncludeFreight: false,
    IncludeTaxAllIn: true,
    IncludeTaxLocal: false,
    IncludeTaxState: false,
    IncludeTaxFederal: false,
    IncludeAllInPrice: true,
  },
  {
    Id: 2,
    CounterPartyId: 1106174,
    CounterPartyName: '3D OIL & LP LLC - 1106174',
    QuoteConfigurationName: 'Delivered',
    ProductIds: Array.from({ length: 116 }, (_, i) => i + 1),
    LocationIds: [1, 2, 3, 4, 5],
    IsActive: true,
    IncludeCounterparty: true,
    IncludeLoadingNumber: false,
    IncludePortalLink: true,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: true,
    IncludeExpirationDate: true,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: true,
    IncludeProductPrice: true,
    IncludeFreight: true,
    IncludeTaxAllIn: true,
    IncludeTaxLocal: true,
    IncludeTaxState: true,
    IncludeTaxFederal: true,
    IncludeAllInPrice: true,
  },
  {
    Id: 3,
    CounterPartyId: 1106176,
    CounterPartyName: 'A-B PETROLEUM INC - 1106176',
    QuoteConfigurationName: 'Contracts',
    ProductIds: Array.from({ length: 116 }, (_, i) => i + 1),
    LocationIds: [1, 2],
    IsActive: true,
    ...DEFAULT_CONTENT_CONFIG,
  },
  {
    Id: 4,
    CounterPartyId: 1104548,
    CounterPartyName: 'ACORN PETROLEUM INC - 1104548',
    QuoteConfigurationName: 'Delivered',
    ProductIds: Array.from({ length: 116 }, (_, i) => i + 1),
    LocationIds: [1, 2, 3, 4, 5, 6, 7],
    IsActive: true,
    ...DEFAULT_CONTENT_CONFIG,
  },
  {
    Id: 5,
    CounterPartyId: 1104549,
    CounterPartyName: 'ACORN PETROLEUM INC - 1104548',
    QuoteConfigurationName: 'Unbranded Rack Prices',
    ProductIds: Array.from({ length: 116 }, (_, i) => i + 1),
    LocationIds: [1, 2, 3, 4, 5, 6, 7],
    IsActive: true,
    IncludeCounterparty: true,
    IncludeLoadingNumber: true,
    IncludePortalLink: true,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: true,
    IncludeExpirationDate: true,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: true,
    IncludeProductPrice: true,
    IncludeFreight: true,
    IncludeTaxAllIn: true,
    IncludeTaxLocal: true,
    IncludeTaxState: true,
    IncludeTaxFederal: true,
    IncludeAllInPrice: true,
  },
  {
    Id: 6,
    CounterPartyId: 1100060,
    CounterPartyName: 'ADAMS PETROLEUM INC - 1100060',
    QuoteConfigurationName: 'Branded Rack Prices',
    ProductIds: Array.from({ length: 116 }, (_, i) => i + 1),
    LocationIds: [1, 2, 3, 4, 5],
    IsActive: true,
    ...DEFAULT_CONTENT_CONFIG,
  },
  {
    Id: 7,
    CounterPartyId: 1100061,
    CounterPartyName: 'ADAMS PETROLEUM INC - 1100060',
    QuoteConfigurationName: 'Delivered',
    ProductIds: Array.from({ length: 116 }, (_, i) => i + 1),
    LocationIds: [1, 2, 3, 4, 5],
    IsActive: true,
    IncludeCounterparty: true,
    IncludeLoadingNumber: true,
    IncludePortalLink: true,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: true,
    IncludeExpirationDate: false,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: false,
    IncludeProductPrice: true,
    IncludeFreight: false,
    IncludeTaxAllIn: true,
    IncludeTaxLocal: false,
    IncludeTaxState: false,
    IncludeTaxFederal: false,
    IncludeAllInPrice: true,
  },
  {
    Id: 8,
    CounterPartyId: 1105947,
    CounterPartyName: 'AGRILAND FS INC - 1105947',
    QuoteConfigurationName: 'Contracts',
    ProductIds: Array.from({ length: 116 }, (_, i) => i + 1),
    LocationIds: Array.from({ length: 12 }, (_, i) => i + 1),
    IsActive: true,
    ...DEFAULT_CONTENT_CONFIG,
  },
  {
    Id: 9,
    CounterPartyId: 1106178,
    CounterPartyName: "AL'S CORNER OIL CO - 1106178",
    QuoteConfigurationName: 'Delivered',
    ProductIds: Array.from({ length: 116 }, (_, i) => i + 1),
    LocationIds: Array.from({ length: 9 }, (_, i) => i + 1),
    IsActive: true,
    IncludeCounterparty: true,
    IncludeLoadingNumber: true,
    IncludePortalLink: true,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: true,
    IncludeExpirationDate: true,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: true,
    IncludeProductPrice: true,
    IncludeFreight: true,
    IncludeTaxAllIn: true,
    IncludeTaxLocal: true,
    IncludeTaxState: true,
    IncludeTaxFederal: true,
    IncludeAllInPrice: true,
  },
  {
    Id: 10,
    CounterPartyId: 1105037,
    CounterPartyName: 'ALLSUPS PETROLEUM INC - 1105037',
    QuoteConfigurationName: 'Unbranded Rack Prices',
    ProductIds: Array.from({ length: 116 }, (_, i) => i + 1),
    LocationIds: [1, 2, 3, 4],
    IsActive: true,
    ...DEFAULT_CONTENT_CONFIG,
  },
  {
    Id: 11,
    CounterPartyId: 1100318,
    CounterPartyName: 'ALON USA LP - 1100318',
    QuoteConfigurationName: 'Branded Rack Prices',
    ProductIds: Array.from({ length: 116 }, (_, i) => i + 1),
    LocationIds: [1, 2, 3, 4, 5, 6],
    IsActive: true,
    ...DEFAULT_CONTENT_CONFIG,
  },
  {
    Id: 12,
    CounterPartyId: 1106177,
    CounterPartyName: 'ALPHA PETROLEUM CO - 1106177',
    QuoteConfigurationName: 'Contracts',
    ProductIds: Array.from({ length: 116 }, (_, i) => i + 1),
    LocationIds: [1],
    IsActive: true,
    ...DEFAULT_CONTENT_CONFIG,
  },
];

// Sample recipient/notification destination data
export const sampleRecipientData: RecipientData[] = [
  {
    CounterPartyId: '1104546',
    CounterPartyName: 'Acme Petroleum Corp',
    SiteIds: ['ACME001', 'ACME002'],
    Emails: ['pricing@acmepetro.com', 'ops@acmepetro.com'],
    OptedOutEmails: [],
  },
  {
    CounterPartyId: '1106174',
    CounterPartyName: 'Blue Sky Energy LLC',
    SiteIds: ['BSE100'],
    Emails: [],
    OptedOutEmails: [],
  },
  {
    CounterPartyId: '1106176',
    CounterPartyName: 'Cascade Fuels Inc',
    SiteIds: [],
    Emails: ['john.smith@cascadefuels.com', 'pricing-team@cascadefuels.com'],
    OptedOutEmails: [],
  },
  {
    CounterPartyId: '1104548',
    CounterPartyName: 'Delta Transport Services',
    SiteIds: ['DTS001', 'DTS002'],
    Emails: ['active@deltatransport.com'],
    OptedOutEmails: [{ email: 'former@deltatransport.com', optedOutDate: '12/15/2025' }],
  },
  {
    CounterPartyId: '1100060',
    CounterPartyName: 'EastCoast Distributors',
    SiteIds: ['ECD001', 'ECD002', 'ECD003'],
    Emails: ['procurement@eastcoast.com', 'logistics@eastcoast.com'],
    OptedOutEmails: [],
  },
  {
    CounterPartyId: '1105947',
    CounterPartyName: 'Frontier Oil Company',
    SiteIds: [],
    Emails: [],
    OptedOutEmails: [],
  },
  {
    CounterPartyId: '1106178',
    CounterPartyName: 'Gulf States Refining',
    SiteIds: ['GSR001'],
    Emails: ['prices@gulfstates.com', 'trading-desk@gulfstates.com', 'mary.johnson@gulfstates.com'],
    OptedOutEmails: [],
  },
  {
    CounterPartyId: '1105037',
    CounterPartyName: 'Highland Petroleum',
    SiteIds: ['HLP001', 'HLP002'],
    Emails: ['notifications@highland.com'],
    OptedOutEmails: [],
  },
];
