import { CompetitorProfile, MetricTileData } from './CompetitorPriceProfiling.types';

export const MOTIVA_PROFILE: CompetitorProfile = {
  id: 'motiva-port-arthur-cbob',
  competitor: 'Motiva',
  publisher: 'OPIS',
  counterpartyGroup: 'Refiner',
  location: 'Port Arthur, TX',
  region: 'Gulf Coast',
  product: 'CBOB',
  productGroup: 'Gasoline',
  classification: 'Premium',
  isLeader: true,
  followers: [
    { name: 'Shell', pValue: 0.001, lag: 1 },
    { name: 'Valero', pValue: 0.003, lag: 2 },
    { name: 'Exxon', pValue: 0.008, lag: 2 },
    { name: 'Chevron', pValue: 0.02, lag: 3 },
    { name: 'Marathon', pValue: 0.04, lag: 3 },
  ],
  passThrough: { up: 92, down: 78 },
  rank: { avg90: 2, avg30: 3 },
  confidences: {
    followers: 'HIGH',
    leader: 'HIGH',
    pricePositioning: 'HIGH',
    passThrough: 'HIGH',
    rank: 'HIGH',
  },
  observations: 90,
};

export const COMPETITOR_PROFILES: CompetitorProfile[] = [
  MOTIVA_PROFILE,
  {
    id: 'shell-houston-ulsd',
    competitor: 'Shell',
    publisher: 'OPIS',
    counterpartyGroup: 'Refiner',
    location: 'Houston, TX',
    region: 'Gulf Coast',
    product: 'ULSD',
    productGroup: 'Diesel',
    classification: 'Premium',
    isLeader: false,
    followers: [
      { name: 'Exxon', pValue: 0.006, lag: 2 },
      { name: 'Chevron', pValue: 0.02, lag: 2 },
    ],
    passThrough: { up: 88, down: 85 },
    rank: { avg90: 2, avg30: 2 },
    confidences: {
      followers: 'HIGH',
      leader: 'MED',
      pricePositioning: 'HIGH',
      passThrough: 'HIGH',
      rank: 'MED',
    },
    observations: 72,
  },
  {
    id: 'exxon-baton-rouge-cbob',
    competitor: 'Exxon',
    publisher: 'OPIS',
    counterpartyGroup: 'Refiner',
    location: 'Baton Rouge, LA',
    region: 'Gulf Coast',
    product: 'CBOB',
    productGroup: 'Gasoline',
    classification: 'Conformist',
    isLeader: false,
    followers: [],
    passThrough: { up: 84, down: 80 },
    rank: { avg90: 4, avg30: 4 },
    confidences: {
      followers: 'MED',
      leader: 'MED',
      pricePositioning: 'MED',
      passThrough: 'MED',
      rank: 'MED',
    },
    observations: 54,
  },
  {
    id: 'valero-corpus-christi-rbob',
    competitor: 'Valero',
    publisher: 'OPIS',
    counterpartyGroup: 'Refiner',
    location: 'Corpus Christi, TX',
    region: 'Gulf Coast',
    product: 'RBOB',
    productGroup: 'Gasoline',
    classification: 'Discount',
    isLeader: false,
    followers: [
      { name: 'Motiva', pValue: 0.004, lag: 1 },
      { name: 'Citgo', pValue: 0.01, lag: 2 },
    ],
    passThrough: { up: 95, down: 70 },
    rank: { avg90: 5, avg30: 4 },
    confidences: {
      followers: 'HIGH',
      leader: 'MED',
      pricePositioning: 'HIGH',
      passThrough: 'HIGH',
      rank: 'HIGH',
    },
    observations: 86,
  },
  {
    id: 'racetrac-atlanta-cbob',
    competitor: 'RaceTrac',
    publisher: 'OPIS',
    counterpartyGroup: 'Retailer',
    location: 'Atlanta, GA',
    region: 'Southeast',
    product: 'CBOB',
    productGroup: 'Gasoline',
    classification: 'Discount',
    isLeader: false,
    followers: [],
    passThrough: { up: 45, down: 60 },
    rank: { avg90: 6, avg30: 6 },
    confidences: {
      followers: 'LOW',
      leader: 'LOW',
      pricePositioning: 'LOW',
      passThrough: 'LOW',
      rank: 'LOW',
    },
    observations: 18,
  },
  {
    id: 'chevron-el-paso-cbob',
    competitor: 'Chevron',
    publisher: 'OPIS',
    counterpartyGroup: 'Refiner',
    location: 'El Paso, TX',
    region: 'Southwest',
    product: 'CBOB',
    productGroup: 'Gasoline',
    classification: 'Premium',
    isLeader: true,
    followers: [],
    passThrough: { up: 90, down: 82 },
    rank: { avg90: 1, avg30: 1 },
    confidences: {
      followers: 'HIGH',
      leader: 'HIGH',
      pricePositioning: 'HIGH',
      passThrough: 'MED',
      rank: 'HIGH',
    },
    observations: 78,
  },
];

export const SUMMARY_TILES: MetricTileData[] = [
  {
    label: 'Tracked competitors',
    value: '12',
    sub: 'across 8 terminals × 6 products',
  },
  {
    label: 'Leaders',
    value: '3',
    sub: 'move first · others follow within 1–3 prices',
  },
  {
    label: 'Premium',
    value: '24',
    sub: '≥ +1.0¢/gal above market · 60%+ of prices',
  },
  {
    label: 'Discount',
    value: '31',
    sub: '≤ −1.0¢/gal below market · 60%+ of prices',
  },
  {
    label: 'Conformist',
    value: '68',
    sub: 'within ±0.5¢ of market · 70%+ of prices',
  },
  {
    label: 'Independent',
    value: '24',
    sub: 'high variance · no persistent side',
  },
];
