export type QuoteConfigRow = {
  id: number
  configurationName: string
  isActive: boolean
  terminal: string
  product: string
  costType: string
  group: string
  strategy: string
  usesMarketMove: boolean
  autoPublishType: string
  netOrGross: string
  allocation: number
  counterparty: string
  competitorCount: number
  tierGroup: string | null
  tierLevel: string | null
}

export const tierGroupOptions = [
  { Value: 'Group A', Text: 'Group A' },
  { Value: 'Group B', Text: 'Group B' },
  { Value: 'Group C', Text: 'Group C' },
]

/** Tier levels are owned by their parent group — each group can have different names and quantities */
export const tierLevelOptionsByGroup: Record<string, { Value: string; Text: string }[]> = {
  'Group A': [
    { Value: 'Tier 1', Text: 'Tier 1' },
    { Value: 'Tier 2', Text: 'Tier 2' },
    { Value: 'Tier 3', Text: 'Tier 3' },
  ],
  'Group B': [
    { Value: 'Platinum', Text: 'Platinum' },
    { Value: 'Gold', Text: 'Gold' },
    { Value: 'Silver', Text: 'Silver' },
  ],
  'Group C': [
    { Value: 'Primary', Text: 'Primary' },
    { Value: 'Secondary', Text: 'Secondary' },
  ],
}

/** Flat list for bulk change (all levels across all groups) */
export const allTierLevelOptions = Object.values(tierLevelOptionsByGroup).flat()

export const quoteConfigData: QuoteConfigRow[] = [
  // Wholesale Config (5 rows)
  {
    id: 1,
    configurationName: 'Wholesale Config',
    isActive: true,
    terminal: 'Houston Term.',
    product: 'Diesel #2',
    costType: 'Contract',
    group: 'Group A',
    strategy: 'ULSD Flat',
    usesMarketMove: true,
    autoPublishType: 'Price',
    netOrGross: 'Net',
    allocation: 85,
    counterparty: 'Acme Corp',
    competitorCount: 3,
    tierGroup: 'Group A',
    tierLevel: 'Tier 1',
  },
  {
    id: 2,
    configurationName: 'Wholesale Config',
    isActive: true,
    terminal: 'Dallas Hub',
    product: 'Unleaded 87',
    costType: 'Instrument',
    group: 'Group A',
    strategy: 'UNL + Diff',
    usesMarketMove: false,
    autoPublishType: 'Margin',
    netOrGross: 'Net',
    allocation: 70,
    counterparty: 'Big Fuel Co',
    competitorCount: 5,
    tierGroup: 'Group A',
    tierLevel: 'Tier 2',
  },
  {
    id: 3,
    configurationName: 'Wholesale Config',
    isActive: false,
    terminal: 'Chicago Term.',
    product: 'Premium 91',
    costType: 'Marker',
    group: 'Group B',
    strategy: 'Market Move',
    usesMarketMove: true,
    autoPublishType: 'None',
    netOrGross: 'Gross',
    allocation: 50,
    counterparty: 'PetroChem Inc',
    competitorCount: 2,
    tierGroup: 'Group B',
    tierLevel: 'Platinum',
  },
  {
    id: 4,
    configurationName: 'Wholesale Config',
    isActive: true,
    terminal: 'Houston Term.',
    product: 'Diesel #2',
    costType: 'Contract',
    group: 'None',
    strategy: 'ULSD Flat',
    usesMarketMove: false,
    autoPublishType: 'Price',
    netOrGross: 'Net',
    allocation: 100,
    counterparty: 'Gulf Energy',
    competitorCount: 0,
    tierGroup: null,
    tierLevel: null,
  },
  {
    id: 5,
    configurationName: 'Wholesale Config',
    isActive: true,
    terminal: 'Dallas Hub',
    product: 'Unleaded 87',
    costType: 'Instrument',
    group: 'Group A',
    strategy: 'UNL + Diff',
    usesMarketMove: true,
    autoPublishType: 'Margin',
    netOrGross: 'Net',
    allocation: 90,
    counterparty: 'SunCoast Fuels',
    competitorCount: 4,
    tierGroup: 'Group A',
    tierLevel: 'Tier 3',
  },
  // Industrial Config (5 rows)
  {
    id: 6,
    configurationName: 'Industrial Config',
    isActive: true,
    terminal: 'Chicago Term.',
    product: 'Diesel #2',
    costType: 'Contract',
    group: 'Group B',
    strategy: 'ULSD Flat',
    usesMarketMove: false,
    autoPublishType: 'None',
    netOrGross: 'Net',
    allocation: 60,
    counterparty: 'Midwest Mfg',
    competitorCount: 1,
    tierGroup: 'Group B',
    tierLevel: 'Gold',
  },
  {
    id: 7,
    configurationName: 'Industrial Config',
    isActive: true,
    terminal: 'Houston Term.',
    product: 'Premium 91',
    costType: 'Marker',
    group: 'None',
    strategy: 'Market Move',
    usesMarketMove: true,
    autoPublishType: 'Price',
    netOrGross: 'Gross',
    allocation: 45,
    counterparty: 'Atlas Industries',
    competitorCount: 3,
    tierGroup: null,
    tierLevel: null,
  },
  {
    id: 8,
    configurationName: 'Industrial Config',
    isActive: false,
    terminal: 'Dallas Hub',
    product: 'Unleaded 87',
    costType: 'Instrument',
    group: 'Group A',
    strategy: 'UNL + Diff',
    usesMarketMove: false,
    autoPublishType: 'Margin',
    netOrGross: 'Net',
    allocation: 75,
    counterparty: 'Sterling Chemical',
    competitorCount: 0,
    tierGroup: 'Group A',
    tierLevel: 'Tier 1',
  },
  {
    id: 9,
    configurationName: 'Industrial Config',
    isActive: true,
    terminal: 'Chicago Term.',
    product: 'Diesel #2',
    costType: 'Contract',
    group: 'Group B',
    strategy: 'ULSD Flat',
    usesMarketMove: true,
    autoPublishType: 'None',
    netOrGross: 'Net',
    allocation: 80,
    counterparty: 'Heartland Power',
    competitorCount: 2,
    tierGroup: 'Group B',
    tierLevel: 'Silver',
  },
  {
    id: 10,
    configurationName: 'Industrial Config',
    isActive: true,
    terminal: 'Houston Term.',
    product: 'Premium 91',
    costType: 'Marker',
    group: 'None',
    strategy: 'Market Move',
    usesMarketMove: false,
    autoPublishType: 'Price',
    netOrGross: 'Gross',
    allocation: 55,
    counterparty: 'Forge Manufacturing',
    competitorCount: 1,
    tierGroup: null,
    tierLevel: null,
  },
  // Retail Config (5 rows)
  {
    id: 11,
    configurationName: 'Retail Config',
    isActive: true,
    terminal: 'Dallas Hub',
    product: 'Unleaded 87',
    costType: 'Instrument',
    group: 'Group A',
    strategy: 'UNL + Diff',
    usesMarketMove: true,
    autoPublishType: 'Margin',
    netOrGross: 'Net',
    allocation: 95,
    counterparty: 'QuikStop Stations',
    competitorCount: 6,
    tierGroup: 'Group A',
    tierLevel: 'Tier 2',
  },
  {
    id: 12,
    configurationName: 'Retail Config',
    isActive: true,
    terminal: 'Houston Term.',
    product: 'Diesel #2',
    costType: 'Contract',
    group: 'None',
    strategy: 'ULSD Flat',
    usesMarketMove: false,
    autoPublishType: 'Price',
    netOrGross: 'Net',
    allocation: 100,
    counterparty: 'FuelMart LLC',
    competitorCount: 4,
    tierGroup: null,
    tierLevel: null,
  },
  {
    id: 13,
    configurationName: 'Retail Config',
    isActive: false,
    terminal: 'Chicago Term.',
    product: 'Premium 91',
    costType: 'Marker',
    group: 'Group B',
    strategy: 'Market Move',
    usesMarketMove: true,
    autoPublishType: 'None',
    netOrGross: 'Gross',
    allocation: 40,
    counterparty: 'Corner Gas Co',
    competitorCount: 2,
    tierGroup: 'Group B',
    tierLevel: 'Platinum',
  },
  {
    id: 14,
    configurationName: 'Retail Config',
    isActive: true,
    terminal: 'Dallas Hub',
    product: 'Unleaded 87',
    costType: 'Instrument',
    group: 'Group A',
    strategy: 'UNL + Diff',
    usesMarketMove: false,
    autoPublishType: 'Margin',
    netOrGross: 'Net',
    allocation: 65,
    counterparty: 'Roadside Energy',
    competitorCount: 3,
    tierGroup: 'Group C',
    tierLevel: 'Primary',
  },
  {
    id: 15,
    configurationName: 'Retail Config',
    isActive: true,
    terminal: 'Houston Term.',
    product: 'Diesel #2',
    costType: 'Contract',
    group: 'None',
    strategy: 'ULSD Flat',
    usesMarketMove: true,
    autoPublishType: 'Price',
    netOrGross: 'Net',
    allocation: 88,
    counterparty: 'Express Petroleum',
    competitorCount: 5,
    tierGroup: 'Group C',
    tierLevel: 'Secondary',
  },
]

export const mockGroups = [
  { id: 1, name: 'Group A' },
  { id: 2, name: 'Group B' },
  { id: 3, name: 'Group C' },
]
