import {
  AppstoreOutlined,
  ShopOutlined,
  DashboardOutlined,
  BookOutlined,
  CalculatorOutlined,
  GlobalOutlined,
  CreditCardOutlined,
  BellOutlined,
  FileTextOutlined,
  SwapOutlined,
  DollarOutlined,
  LineChartOutlined,
  SyncOutlined,
  EditOutlined,
  TableOutlined,
  BgColorsOutlined,
  SmileFilled,
  SettingOutlined,
  UserOutlined,
  TeamOutlined,
  HomeOutlined,
  FolderOutlined,
  CloudOutlined,
  LockOutlined,
  MailOutlined,
  PhoneOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  SearchOutlined,
  FilterOutlined,
  PlusOutlined,
  StarOutlined,
  HeartOutlined,
  ThunderboltOutlined,
  RocketOutlined,
  ToolOutlined,
  ApiOutlined,
  DatabaseOutlined,
  CodeOutlined,
  BranchesOutlined,
  BuildOutlined,
  ExperimentOutlined,
  FundOutlined,
  PieChartOutlined,
  BarChartOutlined,
  AreaChartOutlined,
  ShoppingCartOutlined,
  TrophyOutlined,
  FlagOutlined,
  TagOutlined,
  BulbOutlined,
  SafetyOutlined,
} from '@ant-design/icons';

export interface IconRegistryEntry {
  name: string;
  component: React.ComponentType;
}

export const ICON_REGISTRY: IconRegistryEntry[] = [
  { name: 'AppstoreOutlined', component: AppstoreOutlined },
  { name: 'ShopOutlined', component: ShopOutlined },
  { name: 'DashboardOutlined', component: DashboardOutlined },
  { name: 'BookOutlined', component: BookOutlined },
  { name: 'CalculatorOutlined', component: CalculatorOutlined },
  { name: 'GlobalOutlined', component: GlobalOutlined },
  { name: 'CreditCardOutlined', component: CreditCardOutlined },
  { name: 'BellOutlined', component: BellOutlined },
  { name: 'FileTextOutlined', component: FileTextOutlined },
  { name: 'SwapOutlined', component: SwapOutlined },
  { name: 'DollarOutlined', component: DollarOutlined },
  { name: 'LineChartOutlined', component: LineChartOutlined },
  { name: 'SyncOutlined', component: SyncOutlined },
  { name: 'EditOutlined', component: EditOutlined },
  { name: 'TableOutlined', component: TableOutlined },
  { name: 'BgColorsOutlined', component: BgColorsOutlined },
  { name: 'SmileFilled', component: SmileFilled },
  { name: 'SettingOutlined', component: SettingOutlined },
  { name: 'UserOutlined', component: UserOutlined },
  { name: 'TeamOutlined', component: TeamOutlined },
  { name: 'HomeOutlined', component: HomeOutlined },
  { name: 'FolderOutlined', component: FolderOutlined },
  { name: 'CloudOutlined', component: CloudOutlined },
  { name: 'LockOutlined', component: LockOutlined },
  { name: 'MailOutlined', component: MailOutlined },
  { name: 'PhoneOutlined', component: PhoneOutlined },
  { name: 'CalendarOutlined', component: CalendarOutlined },
  { name: 'ClockCircleOutlined', component: ClockCircleOutlined },
  { name: 'SearchOutlined', component: SearchOutlined },
  { name: 'FilterOutlined', component: FilterOutlined },
  { name: 'PlusOutlined', component: PlusOutlined },
  { name: 'StarOutlined', component: StarOutlined },
  { name: 'HeartOutlined', component: HeartOutlined },
  { name: 'ThunderboltOutlined', component: ThunderboltOutlined },
  { name: 'RocketOutlined', component: RocketOutlined },
  { name: 'ToolOutlined', component: ToolOutlined },
  { name: 'ApiOutlined', component: ApiOutlined },
  { name: 'DatabaseOutlined', component: DatabaseOutlined },
  { name: 'CodeOutlined', component: CodeOutlined },
  { name: 'BranchesOutlined', component: BranchesOutlined },
  { name: 'BuildOutlined', component: BuildOutlined },
  { name: 'ExperimentOutlined', component: ExperimentOutlined },
  { name: 'FundOutlined', component: FundOutlined },
  { name: 'PieChartOutlined', component: PieChartOutlined },
  { name: 'BarChartOutlined', component: BarChartOutlined },
  { name: 'AreaChartOutlined', component: AreaChartOutlined },
  { name: 'ShoppingCartOutlined', component: ShoppingCartOutlined },
  { name: 'TrophyOutlined', component: TrophyOutlined },
  { name: 'FlagOutlined', component: FlagOutlined },
  { name: 'TagOutlined', component: TagOutlined },
  { name: 'BulbOutlined', component: BulbOutlined },
  { name: 'SafetyOutlined', component: SafetyOutlined },
];

const registryMap = new Map(ICON_REGISTRY.map(e => [e.name, e.component]));

export function getIconComponent(name: string): React.ComponentType | null {
  return registryMap.get(name) ?? null;
}

export function searchIcons(query: string): IconRegistryEntry[] {
  if (!query.trim()) return ICON_REGISTRY;
  const term = query.toLowerCase();
  return ICON_REGISTRY.filter(e => e.name.toLowerCase().includes(term));
}
