compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: "${NPM_TOKEN}"

npmScopes:
  gravitate-js:
    npmRegistryServer: "https://registry.npmjs.org"