// Mock data for Content Configuration

import { ContentConfiguration } from './types'

export const mockContentConfigurations: ContentConfiguration[] = [
  {
    QuoteConfigId: 1,
    QuoteConfigName: 'Branded Rack Prices',
    EmailSubject: 'Branded Rack Prices Notification Effective From {EffectiveDate}',
    EmailBody:
      'Dear Customer,\n\nPlease be advised of the posted price changes below:\n\n{Table}\n\nThank you for your business.',
    IncludeCounterparty: false,
    IncludeLoadingNumber: true,
    IncludePortalLink: true,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: true,
    IncludeExpirationDate: true,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: true,
    IncludeProductPrice: true,
    IncludeFreight: true,
    IncludeTaxAllIn: true,
    IncludeTaxLocal: true,
    IncludeTaxState: true,
    IncludeTaxFederal: true,
    IncludeAllInPrice: true,
    LastModified: '2026-01-15T10:30:00',
    ModifiedBy: 'John Smith',
  },
  {
    QuoteConfigId: 2,
    QuoteConfigName: 'Unbranded Rack Prices',
    EmailSubject: 'Unbranded Rack Prices Notification Effective From {EffectiveDate}',
    EmailBody:
      'Dear Customer,\n\nPlease be advised of the posted price changes below:\n\n{Table}\n\nThank you for your business.',
    IncludeCounterparty: false,
    IncludeLoadingNumber: true,
    IncludePortalLink: true,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: true,
    IncludeExpirationDate: true,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: true,
    IncludeProductPrice: true,
    IncludeFreight: true,
    IncludeTaxAllIn: true,
    IncludeTaxLocal: true,
    IncludeTaxState: true,
    IncludeTaxFederal: true,
    IncludeAllInPrice: true,
    LastModified: '2026-01-10T14:22:00',
    ModifiedBy: 'Jane Doe',
  },
  {
    QuoteConfigId: 3,
    QuoteConfigName: 'Contracts',
    EmailSubject: 'Contracts Notification Effective From {EffectiveDate}',
    EmailBody:
      'Dear Customer,\n\nPlease be advised of the posted price changes below:\n\n{Table}\n\nThank you for your business.',
    IncludeCounterparty: false,
    IncludeLoadingNumber: true,
    IncludePortalLink: true,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: true,
    IncludeExpirationDate: true,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: true,
    IncludeProductPrice: true,
    IncludeFreight: true,
    IncludeTaxAllIn: true,
    IncludeTaxLocal: true,
    IncludeTaxState: true,
    IncludeTaxFederal: true,
    IncludeAllInPrice: true,
    LastModified: '2026-01-20T09:15:00',
    ModifiedBy: 'Mike Johnson',
  },
  {
    QuoteConfigId: 4,
    QuoteConfigName: 'Delivered',
    EmailSubject: 'Delivered Price Notification Effective From {EffectiveDate}',
    EmailBody:
      'Dear Customer,\n\nPlease be advised of the posted price changes below:\n\n{Table}\n\nThank you for your business.',
    IncludeCounterparty: false,
    IncludeLoadingNumber: true,
    IncludePortalLink: true,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: true,
    IncludeExpirationDate: true,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: true,
    IncludeProductPrice: true,
    IncludeFreight: true,
    IncludeTaxAllIn: true,
    IncludeTaxLocal: true,
    IncludeTaxState: true,
    IncludeTaxFederal: true,
    IncludeAllInPrice: true,
    LastModified: null,
    ModifiedBy: null,
  },
]
