// Mock data for Content Configuration

import { ContentConfiguration } from './types'

export const mockContentConfigurations: ContentConfiguration[] = [
  {
    QuoteConfigId: 1,
    QuoteConfigName: 'Branded Rack Prices',
    EmailSubject: 'Price Update - {LocationName} - {ProductName}',
    EmailBody:
      'Dear Customer,\n\nPlease be advised that the price for {ProductName} at {LocationName} has been updated.\n\nNew Price: {Price}\nEffective: {EffectiveDate}\n\nThank you for your business.',
    IncludeCounterparty: true,
    IncludeLoadingNumber: true,
    IncludePortalLink: true,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: true,
    IncludeExpirationDate: false,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: false,
    IncludeProductPrice: true,
    IncludeFreight: false,
    IncludeTaxAllIn: true,
    IncludeTaxLocal: false,
    IncludeTaxState: false,
    IncludeTaxFederal: false,
    IncludeAllInPrice: true,
    LastModified: '2026-01-15T10:30:00',
    ModifiedBy: 'John Smith',
  },
  {
    QuoteConfigId: 2,
    QuoteConfigName: 'Unbranded Rack Prices',
    EmailSubject: 'Unbranded Rack Price Update - {LocationName}',
    EmailBody:
      'Price notification for {ProductName}.\n\nLocation: {LocationName}\nPrice: {Price}\nEffective: {EffectiveDate}',
    IncludeCounterparty: true,
    IncludeLoadingNumber: false,
    IncludePortalLink: true,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: false,
    IncludeExpirationDate: false,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: false,
    IncludeProductPrice: true,
    IncludeFreight: true,
    IncludeTaxAllIn: false,
    IncludeTaxLocal: false,
    IncludeTaxState: false,
    IncludeTaxFederal: false,
    IncludeAllInPrice: true,
    LastModified: '2026-01-10T14:22:00',
    ModifiedBy: 'Jane Doe',
  },
  {
    QuoteConfigId: 3,
    QuoteConfigName: 'Contracts',
    EmailSubject: 'Contract Price Update - {ProductName}',
    EmailBody:
      'Your contract pricing has been updated.\n\nProduct: {ProductName}\nNew Price: {Price}\nChange: {PriceChange}\nEffective: {EffectiveDate}',
    IncludeCounterparty: true,
    IncludeLoadingNumber: true,
    IncludePortalLink: false,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: true,
    IncludeExpirationDate: true,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: true,
    IncludeProductPrice: true,
    IncludeFreight: true,
    IncludeTaxAllIn: true,
    IncludeTaxLocal: true,
    IncludeTaxState: true,
    IncludeTaxFederal: true,
    IncludeAllInPrice: true,
    LastModified: '2026-01-20T09:15:00',
    ModifiedBy: 'Mike Johnson',
  },
  {
    QuoteConfigId: 4,
    QuoteConfigName: 'Delivered',
    EmailSubject: 'Delivered Price Notification - {LocationName}',
    EmailBody:
      'Delivered pricing update for your account.\n\n{ProductName} at {LocationName}\nPrice: {Price}\nEffective: {EffectiveDate}',
    IncludeCounterparty: true,
    IncludeLoadingNumber: false,
    IncludePortalLink: true,
    IncludeEffectiveDate: true,
    IncludeEffectiveTime: false,
    IncludeExpirationDate: false,
    IncludeProduct: true,
    IncludeOriginLocation: true,
    IncludeDestinationLocation: true,
    IncludeProductPrice: true,
    IncludeFreight: true,
    IncludeTaxAllIn: true,
    IncludeTaxLocal: false,
    IncludeTaxState: false,
    IncludeTaxFederal: false,
    IncludeAllInPrice: true,
    LastModified: null,
    ModifiedBy: null,
  },
]
