import type { IndexOfferFormulaComponent, IndexOfferMetaData } from '../../../../../ManageOffers.types'
import { generateIndexOfferDisplayName } from '../Components/IndexOfferComponentsColumnDefs'
import type { FormInstance } from 'antd'

export function mapIndexMetadataToSelectorMetadata(indexMeta: IndexOfferMetaData | undefined) {
  if (!indexMeta) return undefined
  const allPriceTypes = Object.values(indexMeta.PublisherPriceTypes || {}).flat()
  return {
    ProductList: indexMeta.Products,
    LocationList: indexMeta.Locations,
    PriceTypeList: allPriceTypes,
    PricePublisherList: indexMeta.PricePublishers,
    PriceInstrumentList: indexMeta.PriceInstruments,
    TradePriceValuationRuleList: indexMeta.TradePriceValuationRules,
    FormulaTemplates: indexMeta.FormulaTemplates || [],
  }
}

export function mapTemplateToComponents(
  templateVariables: any[],
  idRef: React.MutableRefObject<number>,
  metadata?: IndexOfferMetaData
): IndexOfferFormulaComponent[] {
  return templateVariables.map((variable: any) => {
    const component: IndexOfferFormulaComponent = {
      Percentage: variable.Percentage ?? null,
      PricePublisherId: variable.PricePublisherId ?? null,
      PriceInstrumentId: variable.PriceInstrumentId ?? null,
      PriceValuationRuleId: variable.PriceValuationRuleId ?? null,
      PriceTypeCvId: variable.PriceTypeCvId ?? null,
      DisplayName: variable.DisplayName || '',
      IdForGrid: idRef.current++,
      isDisplayNameCustomized: false,
    }
    const autoGeneratedName = generateIndexOfferDisplayName(component, metadata)
    component.isDisplayNameCustomized = !!variable.DisplayName && variable.DisplayName !== autoGeneratedName
    return component
  })
}

export function getTemplateDetailsFromComponents(
  components: IndexOfferFormulaComponent[],
  form: FormInstance
) {
  const formValues = form.getFieldsValue()
  return {
    Name: undefined,
    FormulaTemplateVariables: components.map((c, i) => ({
      ...c,
      IdForGrid: `new-${i}`,
    })),
    ProductId: formValues.ProductId,
    LocationId: formValues.LocationId,
  }
}

export function mapToFormulaMetadata(indexMeta: IndexOfferMetaData | undefined) {
  if (!indexMeta) return undefined
  const allPriceTypes = Object.values(indexMeta.PublisherPriceTypes || {}).flat()
  return {
    Publishers: indexMeta.PricePublishers,
    Instruments: indexMeta.PriceInstruments,
    DateRules: indexMeta.TradePriceValuationRules,
    PriceTypes: allPriceTypes,
    PublisherPriceTypes: indexMeta.PublisherPriceTypes,
  }
}
